### ISSUE TITLE
ENH: Add support for for Soft Deletes (Logical Deletion) ...

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#118]
Something along the lines of:
- A class level annotation to mark entities that use logical deletion.
- Ability to specify for a query to include the logically deleted beans/rows
- Support for both logical/actual deletes (soft/hard deletes)

At the moment @Where can be used but it is a bit limiting for this issue.

**Comment by jwaterloo** [comment]
An alternative and more flexible would be as follows:
1) Allow adding BeanQueryAdapter(s) to the Query interface itself with a lifetime of just the query
2) Further enhance the Query interface for better introspection. Allow us to inspect the currently defined relationships its properties and and filters.
With these enhancements, one iterate over relationships adding the shall delete clause. This would also be useful when doing MVCC multi version concurrency control in the same table where we track every change performed on an entity sort of like the new SQL standard 2011 system versioned tables. Hopefully you can see these are urgently needed features that would improve simplicity.
3) A scoped query modifier would be great too
try(ShallowDeleteBeanQueryAdapter, MVCCBeanQueryAdapter) {
     Query ...
}

**Comment by icode** [comment]
I wait in hope this feautre, it's very useful.

**Comment by rbygrave** [comment]
FYI: Working on this feature at the moment.

**Comment by rbygrave** [comment]
@jwaterloo In regards your comments which I am digesting again ... 

The SQL2011 is now supported (via @History) with the query.asOf(timestamp) and query.findVersions() / query.findVersionsBetween() - this required a lot more than a special query adapter in the end.  Interestingly as you suggest adding the logical delete predicates to a query is done in a similar way to history.  

Anyway, if there is some other feature you wish to request it now needs to go into a new ticket (as this one is being closed off as incorporated into version 6.13.1)

Thanks, Rob.

**Comment by simongodard** [comment]
@rbygrave does this feature support Cascade Soft Deletes? If so, does it mean everything must be "soft deletable" in the dependencies object graph?

**Comment by rbygrave** [comment]
Yes it cascades but only if the target supports soft delete.

From the docs at :
http://ebean-orm.github.io/docs/features/softdelete

Cascading behavior

A soft delete will cascade along the same relationships as a hard delete as
long as the beans support soft delete. If the 'target' bean does not have a
@SoftDelete property (and hence does not support soft delete) then the soft
delete will not cascade to that relationship.

ManyToMany

Soft delete will not cascade to the intersection table of a @ManyToMany.

Draftable

Soft delete will not propagate to the associated "live" row of a @Draftable
entity bean.
