### ISSUE TITLE
ENH: Add support for using where() on bulk Update statements

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#120]
Hi,

I was looking at the option to do createUpdate() on Ebean and noticed
that you have to write the where clause yourself. Is it an option to
use the expression lists from queries for this as well.

So we would get something like:

```java
// can be Update as well of course
Delete delete = Ebean.createDelete(Order.class); 
delete.where().eq("myproperty", "somevalue");

int rows = delete.execute();
```
etc.

This way we can use the same code for select queries and delete
queries.

Would be nice if this would include some option to update as well, but
maybe that's to much to ask for:

```java
Update update = Ebean.createUpdate(Order.class);
update.where().eq("myproperty", "somevalue");
update.setProperty("myproperty", "somenewvalue");
int rows = update.execute();
```
Let me know what you think.

**Comment by icode** [comment]
+1

**Comment by rbygrave** [comment]
Note that for Delete you can now do this via: https://github.com/ebean-orm/avaje-ebeanorm/issues/398

**Comment by wenzhihong2003** [comment]
+1, this is discuss in #459

**Comment by zhangshifeng** [comment]
:+1:

**Comment by rbygrave** [comment]
This only relates to updates now so changing title.

**Comment by wenzhihong2003** [comment]
@rbygrave , has plan to support this future?

**Comment by rbygrave** [comment]
Q: Would I like to support this feature? 
A: Yes.

Q: When might I get to look at implementing it?
A: Not sure. This is not a sponsored feature etc.  I'll need to review all the priorities on all the open issues around 1st March.

**Comment by rbygrave** [comment]
So this has been supported by the addition of UpdateQuery which has some set() methods and uses an underlying Query.

Example 1:
```java

    int rows = server.update(Customer.class);
        .set("status", Customer.Status.ACTIVE)
        .set("updtime", new Timestamp(System.currentTimeMillis()))
        .where()
          .eq("status", Customer.Status.NEW)
          .eq("billingAddress.country", nz)
          .gt("id", 1000)
        .update();
```

Example 2:
```java

    int rows = server
      .update(Customer.class)
        .set("status", Customer.Status.ACTIVE)
        .set("updtime", new Timestamp(System.currentTimeMillis()))
        .where()
          .eq("status", Customer.Status.NEW)
          .gt("id", 1000)
        .update();
```

Note that there is a `setNull()` and `setRaw()` options in addition to the set property in the above 2 examples.

```java
.setRaw("status = coalesce(status, ?)", Customer.Status.ACTIVE)
```
```java
.setRaw("status = coalesce(status, 'A')")
```
```java
.setNull("notes")
```
