### ISSUE TITLE
ENH: Add support for CallableSql executeQuery() returning a list of beans

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#143]
The user would provide the bean type and column mapping (from resultSet to bean properties) and Ebean would do the rest - call executeQuery on the CallableStatement and process the ResultSet.

**Comment by rbygrave** [comment]
I thought this might be a good enhancement but I'm not sure.  I'll close for now and see if there is future demand for it.

**Comment by DashAnalysis** [comment]
hi Rob, I'm interested in mapping the result of a stored proc to a bean - actually I'd like something similar to the hierarchical columnMapping available with RawSqlBuilder.parse(). Is there any other way to achieve this?

**Comment by rbygrave** [comment]
Hi,
Please note that with this project we consider it inappropriate to ask questions via github issues. 

We want all questions/discussions to go to the google group.  This is because we want github issues to represent a "high quality feed of commit changes - bugs, enhancements or refactoring" ... and specifically we want to encourage "watchers" and not spam those watchers with questions and discussions etc.

If you post your question to the google group we can address it there.

Thanks, Rob.
