### ISSUE TITLE
LazyLoad bug with QueryIterator. Getting EntityNotFoundException("Bean has been deleted - lazy loading failed")

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [ebean-orm/avaje-ebeanorm#228]
After updating to eBean 4.5.2 I have a problem with lazy loading.
The code I use is just iterating over items:
```java
		try (QueryIterator<DWPrintjob> iterator =
				db.createQuery(DWPrintjob.class).where().lt(DWPrintjob.PRINTDATE, to).gt(DWPrintjob.PRINTDATE, from).findIterate()) {
			while (iterator.hasNext()) {

				DWPrintjob job = iterator.next();
				DWUser dwu = job.getUser();
				
				if (!isAllowed(dwu)) continue;
...
```
(First iteration is valid and second is invalid - with exception)

Then I get user (DWUser) which is not loaded (only object with setup id field).
In method isAllowed i'm calling getter: getPrefix and eBean is trying load this bean.
```
DefaultBeanLoader.loadBean(LoadBeanRequest) line: 343	
DefaultServer.loadBean(LoadBeanRequest) line: 468	
DLoadBeanContext$LoadBuffer.loadBean(EntityBeanIntercept) line: 194	
EntityBeanIntercept.loadBeanInternal(int, BeanLoader) line: 719	
EntityBeanIntercept.loadBean(int) line: 692	
EntityBeanIntercept.preGetter(int) line: 779	
DWUser._ebean_get_prefix() line: 4	
DWUser.getPrefix() line: 112	
```
After debugging I have checked that in second iteration DLoadBeanContext$LoadBuffer.loadBean(EntityBeanIntercept) I have:
```
/* method paramter */ EntityBeanIntercept ebi.owner=object DWUser with id 2;
LoadBeanRequest req.batch={
  EntityBeanIntercept for object DWUser with id 2 (!=ebi.owner - from the first iteration),
  EntityBeanIntercept for object DWUser with id 2 (==ebi.owner - from second/this iteration),
}
```
(In the first iteration of main loop there was only one EntityBeanIntercept in req.batch)
Then the method DefaultBeanLoader.loadBean(LoadBeanRequest) is executing query for 5 ids (batchSize) with all the same Id's=2.
SQL is returning one result and then:
```java
    for (int i = 0; i < ebis.length; i++) {
      // Check if the underlying row in DB was deleted. Mark this bean as 'failed' if
      // necessary but allow processing to continue until it is accessed by client code
      ebis[i].checkLazyLoadFailure();
    }
```
the first bean is fully loaded (DWUser@2) and the second (DWUser@2) is not, and checkLazyLoadFailure sets lazyLoadFailure = true and then in EntityBeanIntercept.loadBeanInternal(int, BeanLoader) i get exception: throw new EntityNotFoundException("Bean has been deleted - lazy loading failed");

Before updating to 4.5.2 I didn't had any problems with lazy loading. Now there are few of this type.

**Comment by rbygrave** [comment]
FYI: Looking at this ...

**Comment by rbygrave** [comment]
Fixed in 4.5.3

**Comment by Ryszard-Trojnacki** [comment]
Thanks for fixing it. Now (version 4.5.4) it works fine for me.

**Comment by rbygrave** [comment]
Great.  Thanks for the confirmation.
