### ISSUE TITLE
EbeanCacheWarmer timer not canceled

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [ebean-orm/avaje-ebeanorm#229]
I have application (JUnit tests) that are starting and shutting down ebean a lot of times. Each time ebean starts timer com.avaje.ebeaninternal.server.core.DefaultServerFactory:
```java
if (sleepMillis > 0) {
          Timer t = new Timer("EbeanCacheWarmer", true);
          t.schedule(new CacheWarmer(server), sleepMillis);
}
```
which starts a thread which only sleeps after executing this one task.

This Timer should be canceled at server shutdown and/or after execution.

Also this code can make run:
```java
public void run() {
      server.runCacheWarming();
    }
```
after ebean server is down.

**Comment by rbygrave** [comment]
Fixed in 4.5.3
