### ISSUE TITLE
change generics to extends model

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#231]
in my framework use EBean like this

```
User dbUser = User.withFinder().<User>where().eq("email", user.email).findUnique();
```

i want to use 
```
User dbUser = User.withFinder().where().eq("email", user.email).findUnique();
```

can you change interface generics to <M extends T> like this

``
<M extends T> M findUnique();
``

thanks!

**Comment by rbygrave** [comment]
I don't quite understand.  What is the issue with:

User dbUser = User.withFinder().where().eq("email", user.email).findUnique();


... that example doesn't seem to need <M extends T> ?

**Comment by icode** [comment]
@rbygrave em, withFinder method extends from model, and my framework enhance it.

this interface
```
public static <ID, T extends Model> Finder<ID, T> withFinder(String server) 
```

so now use EBean must explicit generics
```
User dbUser = User.withFinder().<User>where().eq("email", user.email).findUnique();
```
or
```
User dbUser = User.<UUID,User>withFinder().where().eq("email", user.email).findUnique();
```

but i think explicit generics is repeat to `User` model , because  withFinder at `User`, and want get `User`

**Comment by rbygrave** [comment]
Sorry, it is still not clear.

You say "withFinder method extends from model" ... can you show me that.
Model is a class and withFinder() is a method so that doesn't make sense to
me yet.

**Comment by icode** [comment]
All right,i don't want use explicit generics.
[This Model interface](https://github.com/icode/ameba/blob/master/src/main/java/ameba/db/model/Model.java#L75])

and sub-model
```
public class User extends Model {
    @Id
    public UUID id;
    @Email
    @NotBlank
    public String email;
    @NotBlank
    public String password;
    @Transient
    public Boolean rememberMe;
}
```
now use this Ebean model
``
User dbUser = User.<UUID,User>withFinder().where().eq("email", user.email).findUnique();
User dbUser = User.withFinder().<User>where().eq("email", user.email).findUnique();
``
but i can enhance `User` class like this
```
public static <ID extends UUID, T extends User> Finder<ID, T> withFinder(String var0) {
```

**Comment by icode** [comment]
can you change it? thanks

**Comment by rbygrave** [comment]
At the moment I still do not understand enough.  I don't understand yet if
they problem you have is a compile problem or something else ... I think
you only want to change Query findUnique() ?

So no, until I understand it I won't change it.

Cheers, Rob.

**Comment by icode** [comment]
My framework like play1,and in my framework auto enhance EBean model class add `withFinder` `withPersiter` static method.

model java source, it can use for DTO and DB model
```
public class User extends Model {

    @Id
    public UUID id;
    @Email
    @NotBlank
    public String email;
    @NotBlank
    public String password;
    @Transient
    public Boolean rememberMe;

}
```

decompiled enhanced `User` model class
```
@Entity
public class User extends Model implements EntityBean {
     //properties ...
     ....
     //getter/setter ..
     ....
     public static <ID extends UUID, T extends User> Finder<ID, T> withFinder(String var0) {
        Finder var1 = Model.getFinderCache(User.class);
        if(var1 == null) {
            try {
                var1 = (Finder)Model.getFinderConstructor().newInstance(new Object[]{var0, UUID.class, User.class});
                Model.putFinderCache(User.class, var1);
            } catch (Exception var3) {
                throw new AmebaException(var3);
            }
        }

        if(var1 == null) {
            throw new NotFinderFindException();
        } else {
            return var1;
        }
    }

    public static <ID extends UUID, T extends User> Finder<ID, T> withFinder() {
        return (Finder)withFinder(ModelManager.getDefaultDBName());
    }
    //EBean orm enhanced method ...
}
```

`Finder` class like EBean `Query<T>` [Finder.java](https://github.com/icode/ameba/blob/master/src/main/java/ameba/db/model/Finder.java)
[Model.java](https://github.com/icode/ameba/blob/master/src/main/java/ameba/db/model/Model.java#L75])

now use `User` model must be cas type or explicit generics, because  `Query<T>` return <T> generics

```
List<User> dbUser = User.withFinder().<User>where().eq("email", user.email).findList();
List<User> dbUser = User.<UUID,User>withFinder().where().eq("email", user.email).findList();
User dbUser = (User) User.withFinder().where().eq("email", user.email).findUnique();
```

but i want to use
``
List<User> dbUser = User.withFinder().where().eq("email", user.email).findList();
User dbUser =  User.withFinder().where().eq("email", user.email).findUnique();
``

**Comment by icode** [comment]
[Model Interface](https://github.com/icode/ameba/blob/master/src/main/java/ameba/db/model/Model.java#L75]) use for IDE coding autocomplete, and enhancing it at ClassLoader load class.So must be cas type or explicit generics for `Query<T>` interface or `QueryIterator<T>` or `ExpressionList<T>` and more.

**Comment by rbygrave** [comment]
What do you mean by "cas type"?
What do you mean by "explicit generics"?  
... I have not heard either of those terms before.

You are only asking for a change for findUnique().  If this is a problem why it is not a problem for findList(), findSet(), findMap(), findEach()?


    public static <ID, T extends Model> Finder<ID, T> withFinder(String server) {
        Finder<ID, T> finder = _getFinder(server);
        if (finder == null) {
            throw new NotFinderFindException();
        }
        return finder;
    }

So your framework requires T extends Model on this method signiture. I guess that is the underlying issue ...

**Comment by icode** [comment]
yes，all method，not only findUnique. can you change all interface method
signiture to <M extend T> ?Better expansion on other framework.I hope
it!thanks
2015年1月17日 上午6:46于 "Rob Bygrave" <notifications@github.com>写道：

**Comment by icode** [comment]
yes£¬all method£¬not only findUnique. can you change all interface method
signiture to <M extend T> ?Better expansion on other framework.I hope it!

What do you mean by "cas type"?
What do you mean by "explicit generics"?

... I have not heard either of those terms before.

You are only asking for a change for findUnique(). If this is a problem why
it is not a problem for findList(), findSet(), findMap(), findEach()?

public static <ID, T extends Model> Finder<ID, T> withFinder(String server) {
    Finder<ID, T> finder = _getFinder(server);
    if (finder == null) {
        throw new NotFinderFindException();
    }
    return finder;
}

So your framework requires T extends Model on this method signiture. I
guess that is the underlying issue ...

¡ª
Reply to this email directly or view it on GitHub
<https://github.com/ebean-orm/avaje-ebeanorm/issues/231#issuecomment-70335173>
.

**Comment by icode** [comment]
Can you change please?  All interface method signiture change to <M extend T> for more framework and  better expansion.

**Comment by icode** [comment]
Please check and merge #253 request.

**Comment by rbygrave** [comment]
To clarify I still do not understand why there is the need to change the generics signature.  I still do not know what do you mean by "cas type"?  I still do not know what do you mean by "explicit generics"?

It seems to me there is probably a different approach to solve your problem - I just have not had time to look at your problem and understand it yet.

Cheers, Rob.

**Comment by icode** [comment]
I use super class `Model`  for IDE autocomplete, `Model.<? extends Model>withFinder`, but implement class is enhance bytecode add `ChildModel.<ChildModel>withFinder` method.
