### ISSUE TITLE
Stored procedures not commited

### ISSUE THREAD

**Issue by twilek** [ebean-orm/avaje-ebeanorm#235]
I have a fairly simple stored procedure that changes some values in a table in my MySQL database (I use mysql-connector-java:5.1.34). I access this stored procedure in this way:

    CallableSql cs = server.createCallableSql("{call my_stored_procedure(?)}");
    cs.setParameter(1, userId);
    server.execute(cs);
    
After tracing the traffic to my database server I can see that the stored procedure is executed but is never committed. I have also tried to create an explicit transaction and pass that to the `execute` method and then commit it myself but without luck.

I have tried to find out why this is happening and it seem like the `connectionEndForQueryOnly` method is returning `CLOSE_ON_READCOMMITTED` instead of `COMMIT`.

Is this an expected behavior, and if so, how do I force a commit? I have tried to set `ebean.transaction.onqueryonly=COMMIT` in my config but that does not seems to help.

I use ebean 4.5.3.

**Comment by rbygrave** [comment]
Can you include the source for my_stored_procedure ? I can then look to
reproduce the issue.

Thanks, Rob.

**Comment by twilek** [comment]
Here is a striped down version of it that still gives the same behaviour

    create procedure my_stored_procedure(in v_user_uuid varchar(100))
    begin
       update users set email = 'newvalue' where uuid = v_user_uuid;
    end

**Comment by rbygrave** [comment]
Ok, reproduced:

23:36:16.802 [main] TRACE org.avaje.ebean.SQL - txn[1002] {call my_stored_procedure(?,?)}
23:36:16.835 [main] DEBUG org.avaje.ebean.SUM - txn[1002] CallableSql label[null] rows[1] bind[10, modBySP, ]
23:36:16.837 [main] TRACE org.avaje.ebean.TXN - txn[1002] Commit - query only

... commit - query only. Problem there ...

**Comment by rbygrave** [comment]
So the problem here is that there is some assumption that addModification(...) would be set in order to tell Ebean what parts of the L2 cache are potentially invalid.  So that is not clear ... and without addModification() the transaction is still considered to be a 'query only' transaction.

The fix is to treat all stored procedures as marking the transaction as not 'query only'.

Created test case:  TestMysqlCallable

**Comment by rbygrave** [comment]
Fixed in 4.5.4
