### ISSUE TITLE
ENH: Add ebean.ddl.initsql=.... to support executing a sql script prior to running the create all DDL  - was - When the scripts generates the evolution, it should generate the create schema too.

### ISSUE THREAD

**Issue by antonini** [ebean-orm/avaje-ebeanorm#246]
When the ebean creates the evolutions for the entities it should create the line of CREATE SCHEMA if applicable.

If it doesn't, the evolution script fails when executed and if adding it manually, on the next step the script will be regenerated (I know I can disable it, but that is not the point right now).

**Comment by rbygrave** [comment]
Perhaps a better approach would be to have pre and post scripts that can be run.  That is, many won't want the schema to be created and dropped ... but in the case of H2/tests then yes. Hmmm.

**Comment by rbygrave** [comment]
So DB Migration is really a different thing.  What we will do here is to enhance the "create all ddl" case which is typically used for running tests.  That is, create the db schema from scratch such that we can run all the tests as developers locally or on a CI server.

As such with this enhancement we can define a sql script to execute prior to the xxx-create-all.sql.

Typically in test-ebean.properties we can now add a ebean.ddl.initsql entry:

```properties

ebean.ddl.generate=true
ebean.ddl.run=true
ebean.ddl.createOnly=true
ebean.ddl.initsql=test.init.sql
ebean.ddl.seedsql=test.seed.sql

```

... and now the test.init.sql script will execute prior to the xxx-create-all.sql and we can do whatever we want included creating a schema etc.  In a similar fashion we can specify a seed sql script to run after the xxx-create-all.sql.
