### ISSUE TITLE
@AttributeOverride at class level not read - was:  @AttributeOverride annotation does not seem to work (Play 2.2.0 - ebean 3.2.2)

### ISSUE THREAD

**Issue by dbremmen** [ebean-orm/avaje-ebeanorm#247]
Hi!

I posted this issue first to: https://github.com/playframework/playframework/issues/3936 but I was told to post the issue here, maybe somebody can help :)
I don't know if this is a play or ebean issue. I'm using ebean 3.2.2 version.
Here is the story:

I'm trying to use @AttributeOverride to use a different database column name in a subclass but it doesn't seem to work. I tried everything but with no good results :(

I Have a base class like this:
```
@MappedSuperclass
public class BaseProject extends Model {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long id;

    public String name;
}
```
And a subclass:
```
@Table(name = "cmp_alienproject")
@Entity
@AttributeOverride(name="name", column=@Column(name = "APRJ_NAME"))
public class AlienProject extends BaseProject {
   
    public static Finder<Long, AlienProject> find = new Finder<Long, AlienProject>(Long.class, AlienProject.class);
   
    @Required
    @Column(name = "APRJ_PATH")
    public String path;

}
```
When I try to save the entity using the following code:

```
AlienProject project = new AlienProject();
project.name = "test";
project.save();
```

The following error is displayed:

play.api.Application$$anon$1: Execution exception[[PersistenceException: ERROR executing DML bindLog[] error[Unknown column 'name' in 'field list']]]

So It seems that the AttributeOverride takes no effect.. I'm really lost, I tried to move the AttributeOverride in different areas of the sublcass but it always fails with the same error

**Comment by rbygrave** [comment]
Ok.  I have not seen that use of @AttributeOverride before ... no that
won't work as you intend.

As a workaround you can move the name property from BaseProject and add it
to each subclass.

I'll have a look at the JPA spec and confirm if what you are attempting is
valid. Generally @AttributeOverride is useful for @Embedded beans and hence
I've never seen it used in this manor.


Cheers, Rob.

**Comment by dbremmen** [comment]
Thanks a lot rob!
Yes I tried to add the attribute to each subclass but I'm not able to
change the column name, it use the attribute in the superclass always.
Mainly what I want to do is to have a superclass where I can set values
that use different column names in each subclass, maybe there is some other
way of doing that that I don't know.
Best Regards!
 David

**Comment by rbygrave** [comment]
*> Yes I tried to add the attribute to each subclass but I'm not able
tochange the column name, it use the attribute in the superclass always.*

I don't follow that.  If you remove the attribute from the superclass
completely ... it only appears in each subclass, and in each subclass you
can use @Column to specify the column name in each subclass.

That is perhaps not ideal but it is a workaround.  Does that make sense?

Cheers, Rob.

**Comment by dbremmen** [comment]
Yes sorry I mean I keep the attribute in the parent class and the
subclasses. In some point of the code I have the base class in my hand and
I want to set properties and after that save the instance. If I add the
attributes only in the subclasses I cannot do that

**Comment by rbygrave** [comment]
You can still do it under normal circumstances, by either making the base
class abstract with an abstract setName(String name) method or add an
interface with the setName(String name) method ...

So yes, you don't have normal setter/getter pairs as those are generated
for you by Play ... but it were not for that you could still use that
workaround I believe. As a slight alternative to that you could add an
abstract setCommonName(String name) method ... and implement that on each
subclass for example.
