### ISSUE TITLE
JPA 2.x

### ISSUE THREAD

**Issue by gdude2002** [ebean-orm/avaje-ebeanorm#251]
Hey,

I'm not a user of this library, but I develop addons/plugins for various applications. One such application I'm working with depends on this library, but I notice that it only includes a JPA-1.x-compatible `javax.persistence` in the POM.

Unfortunately, that means that anything that depends on the library can't easily support addons/plugins that require JPA 2.x features.

So, what're the reasons for sticking only with the 1.x API? Is there a problem with using [Eclipse's API](http://mvnrepository.com/artifact/org.eclipse.persistence/javax.persistence) or [Hibernate's API](http://mvnrepository.com/artifact/org.hibernate.javax.persistence)? If this dependency can't be changed, what would be a good fix to advise people in similar situations?

**Comment by rvowles** [comment]
ebean is an alternative to Eclipse and Hibernate. Only a portion of JPA 1.x is used, JPA 2.x makes no sense. ebean is not a JPA implementation.

**Comment by rbygrave** [comment]
Just as a slight clarification.

There are some parts of JPA 2.x that we don't yet support in Ebean that we
do want to support (Extra mapping options like @ElementCollection etc) and
there is some extra API to support such as the additional locking options
in JPA 2.x.

So in that sense there are enhancement requests logged to support JPA 2.x
features.  Until that is implemented the dependency is JPA 1.x as it is
currently.

Currently the focus is updating the documentation and later this year we
can look to address the JPA 2.x features.


Cheers, Rob.

**Comment by gdude2002** [comment]
> ebean is an alternative to Eclipse and Hibernate
> ebean is not a JPA implementation

Then ebean isn't an alternative to the two specific libraries I linked.

> [Everything from @rbygrave]

Alright, I see. It's just annoying since the JPA 1.x dependency being shaded into the application JAR seems to override any JPA 2. dependency shaded into addon/plugin JARs in this particular instance - I'm not sure what other alternative to take or whether the devs can fix that, though.

**Comment by rbygrave** [comment]
*> JPA 1.x dependency being shaded into the application JAR seems to
override any JPA 2.*
The dev's could exclude the JPA 1.x dependency for example.

**Comment by rvowles** [comment]
As @rbygrave says, just set an exclusion for the JPA 1 library and you are set.

If you are using Shade for a deployable jar, also potentially consider Spring Boot Loader, its a much better alternative to Shade.

**Comment by gdude2002** [comment]
The project isn't mine, so I don't really have that option o/

I doubt they'd do it either, to be honest. I'll ask them, though.

**Comment by rvowles** [comment]
I don't understand, you can exclude it from the dependency in *your* plugin. If you depend on library X and it depends on eBean, you just put an exclusion in library X for the JPA1 library and it will apply transitively, then you can specifically include the JPA 2.x one. 

You speak of Shade, so the implication is Maven, so you can do this. Or is the library you are using already shaded?

**Comment by gdude2002** [comment]
No, no, let me try to explain better.

Let's say there's a project, we'll call it Spigot, that depends on ebean and shades it and its dependencies into its main JAR.

Let's say, then, that I write a plugin for Spigot that uses Hibernate or some other library that uses JPA 2.x annotations, or similar. I'll shade my libraries into my JAR.

Spigot loads my plugin, which contains a JPA 2.x dependency, but that dependency has a namespace conflict with the JPA 1.x dependency already included in Spigot, causing some errors.

Someone with a similar problem using Hibernate posted [this StackOverflow question](https://stackoverflow.com/questions/3612254/why-does-hibernate-throw-exception-java-lang-nosuchmethoderror-javax-persisten), which might provide some context (although they aren't using ebean).

**Comment by rvowles** [comment]
Right, so Spigot is shafting you by shading. :-)

So can you jarjar your dependencies before you include them in your plugin, therefore automatically changing their namespaces and preventing the clash. Thats all I can think of :-(

**Comment by gdude2002** [comment]
Hmm.. That looks like a possibility. I'll look into it, thanks for the help \o/

**Comment by md-5** [comment]
@gdude2002 here from the Spigot bug tracker - as mentioned above whenever you include a depend you should change its namespace, regardless of whether or not we already have it in our native classpath.

**Comment by gdude2002** [comment]
Oh, hey @md-5, that was.. Actually a lot faster than I was expecting, lol.

Yeah, I'm gonna look into doing that. Thanks for the quick response.

**Comment by rbygrave** [comment]
I think I can close this issue now. Doing so.

Cheers, Rob.
