### ISSUE TITLE
Add expression Exists, Not Exists

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [ebean-orm/avaje-ebeanorm#256]
In Ebean SQL command "EXISTS" and "NOT EXISTS" (not exists could be make with not expression) is not avaible in ExpressionFactory.

**Comment by Ryszard-Trojnacki** [comment]
I have made this enhancement but it requires patch "alias".
All of this is in pull request: https://github.com/ebean-orm/avaje-ebeanorm/pull/257

**Comment by rbygrave** [comment]
Looks good. I'll look to merge it tomorrow night.

Cheers,Rob.

**Comment by rbygrave** [comment]
The associated pull request was merged in so closing this one.
