### ISSUE TITLE
Missing Inserts for Large Batches - Ebean 3.2.2

### ISSUE THREAD

**Issue by evanthomjd** [ebean-orm/avaje-ebeanorm#258]
I have recently noticed an anomaly running concurrent large batched transactions with Ebean 3.2.2. The basic set up is as follows 3-6 transactions are run concurrently, each transaction inserts 50000 records into the same table and each transaction has a  batch size of 1000. It is important to note that to save each new record I am saving the Beans directly, calling Ebean.save.  About 75% of the time this will run without incident, but every so often when every transaction finishes the database will be missing a couple records (so far I've seen as few as 1 and as many as 10).  

 I've traced through the code and it seems that in com.avaje.ebeaninternal.server.persist.BatchedBeanHolder.java in the *append* method there is call to System.identityHashCode and the result of this call is used to determine if the current bean has all ready been added to the persist list. It is my understanding that because of the  large number of objects I am processing there are collisions when System.identityHashCode  is called (http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6809470), causing Ebean to believe it has all ready added a bean to the persist list when in fact it has not. 

Currently I am processing my batch inserts using UpdateSql in place of persisting the beans directly to avoid losing any inserts. I am wondering if anyone else has experienced this problem, or is my current implementation a rare use case?

**Comment by rbygrave** [comment]
Interesting.  No I have not heard anyone report this issue before. I'll
have a look at it.

Cheers, Rob.

**Comment by rbygrave** [comment]
>  batch size of 1000
So yes there is a problem here. If the batch size is large (like 1000) then the chance of this increases. I think this current mechanism needs to change to use an IdentityHashMap -  I'll look to do that.

**Comment by rbygrave** [comment]
Fix for this included in the 4.5.6 release.
