### ISSUE TITLE
_ebean_getIntercept().setNewBeanForUpdate() api not apply

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#261]
use `setNewBeanForUpdate` api not apply, `getChanged()` not change all property
```
        ((EntityBean) model)._ebean_getIntercept().setNewBeanForUpdate()
```
must be use
```
        EntityBeanIntercept intercept = ((EntityBean) model)._ebean_getIntercept();
        for (int i = 0; i < intercept.getPropertyLength(); i++) {
            intercept.markPropertyAsChanged(i);
        }
```

**Comment by rbygrave** [comment]
No, the current behavior is exactly correct and this suggestion is incorrect.
That is, only properties that have been 'loaded' are included in the update. This does include properties that have had their value set to null.

Refer to TestStatelessUpdate.test()

**Comment by rbygrave** [comment]
Closing, no change required - working as required.
