### ISSUE TITLE
Trouble with class hierarchy since fix #169

### ISSUE THREAD

**Issue by mgoellnitz** [ebean-orm/avaje-ebeanorm#263]
When I tried to migrate to a newer version than 4.1.2 I ran into trouble with my very simple test classes at

https://github.com/mgoellnitz/tangram/tree/master/ebean/test/org/tangram/ebean/test/content

BaseClass and SubClass (were SubClass obviously extends BaseClass) are both non abstract classes and supposed to be @Entity classes. On initialisation ebean complains that BaseClass as the superclass for SubClass should not be marked @Entity but @MappedSuperclass.

What am I missing?

**Comment by rbygrave** [comment]
With inheritance ... the beans should either using MappedSuperclass OR use JPA inheritance annotations.  

That is, if you are using inheritance (and not @MappedSuperclass) then you should have @Inheritance
and @DiscriminatorValue etc.

Cheers, Rob.
