### ISSUE TITLE
ClusterManager isn't in public api

### ISSUE THREAD

**Issue by mrock42** [ebean-orm/avaje-ebeanorm#268]
ClusterManager is under the "ebeaninternal" package: com.avaje.ebeaninternal.server.cluster.  It seems as if it should be under com.avaje.ebean package instead since it exposes methods that aren't meant for users to use directly.

**Comment by rbygrave** [comment]
At this point ClusterManager does not need to be in the public API.  There is the BootupEbeanManager interface which maybe would have been better named to 'Container' or 'EbeanContainer'.  The implementation BootupEbeanManager controls clustering, creating EbeanServer instances and shutdown.  At this stage there are no clustering methods that need to be added / exposed via BootupEbeanManager (but that is where they should go I believe).

It is tempting to rename BootupEbeanManager to EbeanContainer - hmmm.

I'll close this for now but re-open or add a comment to discuss further.

Cheers, Rob.

**Comment by mrock42** [comment]
For the website docs, I could only find API docs on ClusterManager, and examples using that in the test cases.  

I'll create better clustering docs and do a pull request. Is below the correct usage for setting up a clustered server? 

```java
private ContainerConfig createContainerConfig(String local, String threadPoolName) {
    ContainerConfig container = new ContainerConfig();
    container.setMode(ContainerConfig.ClusterMode.SOCKET);  // also CusterMode.MULTICAST

    ContainerConfig.SocketConfig socketConfig = new ContainerConfig.SocketConfig();
    socketConfig.setLocalHostPort(local);
    socketConfig.setThreadPoolName(threadPoolName);
    socketConfig.setMembers(Arrays.asList("127.0.0.1:9876", "127.0.0.1:9866"));

    container.setSocketConfig(socketConfig);
    return container;
  }
ContainerConfig containerConfig = createContainerConfig("127.0.0.1:9876", "pool0");

ServerConfig config = new ServerConfig();
...
config.setContainerConfig(containerConfig);
EbeanServer ebean = EbeanServerFactory.create(config); 
```
