### ISSUE TITLE
ENH: Add support for wildcard / startsWith jar searching

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#269]
from discussion:

I'd suggest probably change ClassPathSearchFilter line 180 from

if (match.contains(val)) {

to:

if (val.startswith(match)) {

... as that would be simple and sufficient.   So "ent-model" would match "ent-model-1.2.3.jar"
That avoids the need for regex or wildcard handling.  I believe the common required case is 'starts with'

**Comment by rbygrave** [comment]
Actually this already works in that if you register the jars to search without the ".jar" suffix then it will effectively wildcard search.

So ebean.search.jars=fooBar

will match all of these (exact, with suffix, with prefix):
fooBar.jar
fooBar-1.3.jar
something-fooBar-1.3.jar

This means there is no change required.

**Comment by rvowles** [comment]
That does not work if your classpath code does not understand the classpath
string, which I believe is why I changed it to contains. I believe all the
university apps using ebean will now break.

**Comment by rbygrave** [comment]
There was actually no change to the code.  That is, the associated commit for this issue only added a unit test - the test confirmed that we didn't need to add the 'starts with' and in fact the current 'contains' supports what we need.

So no code change means it should be all good (and will not break apps etc).
