### ISSUE TITLE
ENH: Add support for starting database ids (IDENTITY / AUTO_INCREMENT) at a custom value.

### ISSUE THREAD

**Issue by KoenDG** [ebean-orm/avaje-ebeanorm#273]
I asked the following question on Stackoverflow: http://stackoverflow.com/questions/29494895/

But after some searching came to the conclusion that this functionality just doesn't exist and thus I am requesting it here.

Basically, in Java, a Long object will fail to give the expected comparison of numbers if they are below -128 or above 127. 

So this code:

    Long a = 128;
    Long b = 128;

    System.out.println(a == b)

Will output `false`. While anywhere between and including -128 and 127, it will be `true`.

It would be really useful to make sure the problem of the Java Long values not matching above 127 with the == comparator is detected. I know it;s a best practice to use equals, I'm just requesting this for ease of use in unit testing.

**Comment by rbygrave** [comment]
It is not clear exactly what functionality you are requesting for.  Can you
try and state what change to Ebean ORM you are requesting.

Cheers, Rob.

**Comment by KoenDG** [comment]
What I'm requesting is that when a table is created, the AUTO_INCREMENT counter starts at a higher number than the default 1.

The ability to set this for all tables being created.

**Comment by rbygrave** [comment]
That would depend on the database.  Postgres SERIAL does not support such a feature nor MySql AUTO_INCREMENT so it seems this is not possible for those 2 databases anyway.

Do you have a specific DB with some DDL that actually does this?

**Comment by KoenDG** [comment]
No, I actually just assumed that this is core functionality for all existing dbs.

Although I haven't tried it yet, a person replying to my question on Stackoverflow says that it actually is possible for MySQL with the statement: `ALTER TABLE <table_name> AUTO_INCREMENT = 200;`

I'll try it out on a VM.

**Comment by rbygrave** [comment]
I have added #275 ... which adds support for DDL generation to take into account @SequenceGenerator initialValue.

**Comment by rbygrave** [comment]
I'm reviewing this issue which is now a year old.

**My question is should we just close this issue? **

That is, we don't want to add any unnecessary complexity to Ebean.  Features have to justify their existence and provide enough value to offset the additional complexity and effort they add.  I don't think this feature is justified.

Does someone want to push for this feature?  Does someone want to sponsor it's development?  It not we should close it.

Comments welcome. Thanks, Rob.

**Comment by KoenDG** [comment]
Hello Rob,

I recently had need for this and I just did it manually. That is, capture the generated SQL and put a "restart with ..." statement at the end for the table in question.

Does this need to be part of Ebean?

I don't think it's Ebean's responsibility to make people aware of this behavior of Java.
Namely that == comparisons of 2 object Integer/Long/... outside the default caching range actually compares the toString of the instance pointer, instead of the numerical value.

There's a pretty thorough explanation here: http://stackoverflow.com/a/20948389/80907

I think this is more likely something that static code analysis tools could point out with a warning.

**Comment by rbygrave** [comment]
Ok. I think we should then close this issue.

If we change our minds and what to raise it again we can look to reopen etc.

Thanks, Rob.
