### ISSUE TITLE
sqlQuery support sql page limit on all Database platform

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#279]
how to use SqlQuery for sql page limit on all Database platform

**Comment by rbygrave** [comment]
I think this is effectively a duplicate of #278.  That is, SqlQuery currently does not modify the SQL (using LIMIT/OFFSET or similar) to support paging.

So the answer is, it currently does not support paging.

However, via #278 we should add support for paging to SqlQuery by modifying the SQL as necessary (with LIMIT OFFSET etc).

**Comment by rbygrave** [comment]
Closing this issue - refer to #278 for a fix.
