### ISSUE TITLE
ENH: Add ServerConfig.setJsonInclude(...)  ALL, NON_NULL, NON_EMPTY -  Add support for suppressing properties that have null values from JSON output aka Jackson mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY)

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#280]
config ebean and jackson
```
mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
final JsonFactory jsonFactory = mapper.getFactory();
ebeanServerConfig.setJsonFactory(jsonFactory);
```

but write value
```
{"prop":null}
```

**Comment by rbygrave** [comment]
Note that JsonInclude.Include.NON_EMPTY is a setting for ObjectMapper.  EbeanORM does NOT use ObjectMapper but instead uses the generator and parser from jackson-core.  This is why that setting is not working.

This becomes an enhancement request.  You want EbeanORM to be able to support similar behavior such that properties that have a value of null are not included in the JSON response.

Also note that it is my opinion that the requested behavior is not advisable (in that if you 'apply' the response to an existing javascript object properties that strictly speaking should be null are left as their original value).  I'd not recommend suppressing null values for an AngularJS application for example.

**Comment by icode** [comment]
Null or 0 length String is meaningless for js or html display. Fore-end optimize is useful.

**Comment by rbygrave** [comment]
*> Null or 0 length String is meaningless for js*

I disagree.  If you build a javascript application that uses a function
like: https://docs.angularjs.org/api/ng/function/angular.extend  ... then
you should see that returning a null value is indeed significant (in terms
of applying changes from the response object onto  an another object).

*> ... or html display*

If you restrict the comment to 'display' ONLY then that is a fair enough
statement.

... but If you are building an 'Application' then you should be wary of
suppressing null values.  It is not something I'd do when building an
AngularJS application for example.

**Comment by icode** [comment]
A json to HTML Table display does not show null value.

At js language !!null == undefine == !!'' == false, so most of the time not need null value

**Comment by rbygrave** [comment]
As I said before ... IF you are only displaying then sure that statement is
fair enough.

However, every single SPA application I have built has used angular.extend
or equivalent function and with that null is significant (suppressing the
properties with null values will given you incorrect behavior).

**Comment by icode** [comment]
*> ... every single SPA application I have built has used angular.extend

As I said before ... most of the time i not use `if(json.attr == null)` but `if(json.attr)`
Javascript is weakly typed language. less of the time like `ng.extend` API need keep source props value use `json.hasOwnProperty`, but can use `extend(org,{prop:null},{prop:1})`.

**Comment by rbygrave** [comment]
So there is now JsonConfig.Include with values:  
```java
  public enum Include {

    /**
     * Include all values including null and empty collections.
     */
    ALL,

    /**
     * Exclude null values (include empty collections).
     */
    NON_NULL,

    /**
     * Exclude null values and empty collections.
     */
    NON_EMPTY
  }
```

JsonConfig.Include can be set on JsonWriteOptions for a specific request and the global default is set on ServerConfig.

**Comment by rbygrave** [comment]
Example:
```java
    JsonWriteOptions options = new JsonWriteOptions();
    options.setInclude(JsonConfig.Include.NON_EMPTY);

    String asJson = Ebean.json().toJson(bean, options);
```

**Comment by icode** [comment]
Thanks a lot;
