### ISSUE TITLE
ENH: support disable search classes config via ServerConfig.setDisableClasspathSearch(true)

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#285]
Now `ServerConfig.classes == null || ServerConfig.classes.size()==0` begin search class path models, but i want use SQL select database.

I want has a `ServerConfig.setSearchModel(boolean)` API to disable search class path.

**Comment by rbygrave** [comment]
I don't understand how that would be used.

If classes is null or empty ... and the class path search is disabled ... then EbeanServer would start up with no entity bean classes registered?  Is that what you want to do?

**Comment by icode** [comment]
yes, i want to use only sqlQuery.
