### ISSUE TITLE
ENH: Add ability to validate a query or property expression - Was Please check column exist on entity

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#291]
Please check or exclude `Query.orderBy`, `ExpressionList.eq` etc API path/property on entity.
If check, please throw `PropertyNotExistsException`.

Thanks!

**Comment by rbygrave** [comment]
So no that is actually a feature allowing any DB functions to used
naturally within the expression language. I won't change Ebean to throw a
PropertyNotExistsException and instead allow the query to execute and fail
with some DB error unless there is some very good reason.

I don't understand the CheckRowCountException, you'll need to explain that
better with a use case.

Also note that you should not put 2 separate issues into a single ticket.
There should only be 1 issue raised / resolved per ticket.


Cheers, Rob.

**Comment by icode** [comment]
1rd issue, can provide a utils check this?

OK, please see #292 2rd issue .

**Comment by icode** [comment]
I set orderBy from JAX-RS query params, so i need a info for front-end user DB error.

**Comment by rbygrave** [comment]
> I set orderBy from JAX-RS query params, so i need a info for front-end user not a DB error.

Ok I understand now why you are wanting this feature. So perhaps have a 'strict mode' on the Query or a separate utility to validate properties/expressions.

**Comment by icode** [comment]
thanks, but  'strict mode' need support fragment Expression e.g. `query.where().eq('c1',1)...strictFragment().eq('notExitst',0)`. Then only check strict fragment expression.

thanks.

**Comment by rbygrave** [comment]
So I'm adding 2 mechanisms.

1. Query.validate()
```java

    Query<Customer> query = Ebean.find(Customer.class)
        .where()
          .eq("junk","blah")
          .eq("name","jim")
        .orderBy("id desc,path.that.does.not.exist,contacts.group.name asc");

    Set<String> unknownProperties = query.validate();
    assertThat(unknownProperties).isNotEmpty();
    assertThat(unknownProperties).hasSize(2);
    assertThat(unknownProperties).contains("junk","path.that.does.not.exist");

```

2. SpiBeanType.validateExpression()

```java

    EbeanServer defaultServer = Ebean.getDefaultServer();
    SpiServer pluginApi = defaultServer.getPluginApi();

    SpiBeanType<Customer> custType = pluginApi.getBeanType(Customer.class);

    // these properties / paths are valid (for Customer)
    assertTrue(custType.isValidExpression("name"));
    assertTrue(custType.isValidExpression("contacts.firstName"));
    assertTrue(custType.isValidExpression("contacts.group.name"));

    // these properties / paths are not valid (for Customer)
    assertFalse(custType.isValidExpression("junk"));
    assertFalse(beanType.isValidExpression("Name"));
    assertFalse(custType.isValidExpression("contacts.name"));

```

In the case of needing support fragment Expression e.g. ... you can remove the set of properties/paths from the set that an be ignored.  In the case above:

```java
    Query<Customer> query = Ebean.find(Customer.class)
        .where()
           .eq("c1",1)
           .eq("junk","blah")
           ...

    Set<String> invalid = query.validate();

  // consider "c1" as valid
  invalid.remove("c1");

  // if !invalid.isEmpty() ...


```

**Comment by icode** [comment]
Can i exclude (not ignore)  invalid props and continue query?

**Comment by rbygrave** [comment]
The query will execute if you run it.  Before you run the query you can
call validate() and get the set of properties Ebean does not know about ...
and at that point your application code can then choose to execute the
query or return some error to the user.

**Comment by icode** [comment]
Maven is deploy？

**Comment by rbygrave** [comment]
Yes it has been released to maven central - the associated milestone is 6.12.1.  The latest release is 6.12.1.
