### ISSUE TITLE
 please throw a CheckRowCountException

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#292]
`com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(int rowCount)` please thorw a `CheckRowCountException` because i need a specific error. like give front-end users
now,be bound to use this try cach
```
if (e instanceof OptimisticLockException) {
            if ("checkRowCount".equals(e.getStackTrace()[0].getMethodName())) {
                if (process != null)
                    return process.call();
            }
 }
```

**Comment by rbygrave** [comment]
At this stage this issue does not make sense to me.  That is, the OptimisticLockException is intended for the case where optimistic locking / optimistic concurrency checking fails - it fails based on the updated/deleted row count not being the expected value.

That is, I don't see why you see the need for a different exception.

**Comment by icode** [comment]
So, all optimisticlockexception is checkRowCount error?

**Comment by icode** [comment]
i need get RowCount for http POST request. If RowCount is zero, i need insert a entity.

**Comment by rbygrave** [comment]
Yes - that is what a OptimisticLockException is  (there is no DB involved
which is why many call it 'optimistic concurrency checking').

**Comment by icode** [comment]
ebean now and afterwards not have `optimistic lock`?

**Comment by rbygrave** [comment]
*> If RowCount is zero, i need insert a entity.*

That sounds like 'upsert' (which some db's support in various ways but
there are implementation specific issues with 'upsert').  You should
explain more fully what you are trying to achieve.

**Comment by rbygrave** [comment]
*> ebean now and afterwards not have optimistic lock?*

Ebean has always had optimistic locking.  Ebean also has pessimistic
locking (which results in real DB locks - "select for update").

**Comment by icode** [comment]
but optimistic lock not use OptimisticLockException?

Now i use jersey(JAX-RS) for RESTful service, so http `PATCH` should replace model, if model not exist insert model, exist update model all properties.

And have a force all properties method api?
