### ISSUE TITLE
ElasticSearch Integration - part 1 - updating indexes

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#304]
For ElasticSearch integration this first part adds features that update indexes.  Beans are annotated with @ElasticIndex with various options for controlling the behavior of inserts, updates and deletes to either update the index via ElasticSearch Bulk API or queuing the event for later processing.

**Comment by icode** [comment]
has a only Lucene support? like ebean2

**Comment by rbygrave** [comment]
Perhaps you can ask your question again (I did not understand) but ... this
feature specifically supports ElasticSearch and makes use of the
ElasticSearch API's (Bulk update etc) and does not attempt to use Lucene
directly.

Q: Is there going to be direct support for Lucene in Ebean?
A: No, I've been there before and it is way too painful and ElasticSearch
is a much much much better solution to integrate with.

Q: Why do we love Lucene/ElasticSearch?
A: We want to use Inverted indexes
     ... we want text search
     ... we want to be able to take load off the DB
     ... we want Level 3 cache (L2 query cache invalidates quickly)

Q: But what about SOLR?
A: In New Zealand we would say "Yeah, nah" ... which here means "yes it is
an option, no I don't think it is a good option."


Now very large ElasticSearch clusters are not 'trivial'.  There is
potential for issues and 'oh darn' moments but I have faith that this is
the correct path/product to integration with.


Background:
-----------------
So yes, the very first version of Ebean some 8+ years ago used Lucene
directly.  A few years ago (4 years ago I think) I was working on updating
the Lucene support in Ebean and found out about ElasticSearch (and yes I
have also used SOLR). Now in my experience using Lucene directly is
relatively painful in a number of areas and ElasticSearch does some really
good things that are not easy in order to take that pain away.

Shay Banon who leads ElasticSearch previously wrote Compass and so there is
some very good knowledge and experience that proceeds ElasticSearch.



Cheers, Rob.

**Comment by wenzhihong2003** [comment]
this future is complete developed? when to merger master?

**Comment by rbygrave** [comment]
There is a bit more work to be done.  I might not get back to this for a
week or so.

**Comment by icode** [comment]
We are waiting it! :+1:

**Comment by dhirenpratap** [comment]
Waiting Waiting :+1:

**Comment by rbygrave** [comment]
Getting close now - this is what I've been working on for the past while.
