### ISSUE TITLE
Add back support for JsonValueAdapter and JsonReadOptions into 4.x

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#307]
These features got removed in 4.x ... we want them back.

**Comment by PR-O** [comment]
Hi @rbygrave , I guess you haven't had any time yet to look at this issue. Is there a timeline? Unfortunately we're kind of stuck without it.

**Comment by rbygrave** [comment]
Looking at it now ... making good progress. You don't need JsonValueAdapter right?  ... so just JsonReadBeanVisitor and JsonReadOptions? 

Note for JsonReadBeanVisitor ... JsonElement is going to become Object so:

```java

public interface JsonReadBeanVisitor<T> {

  void visit(T bean, Map<String, Object> unmapped);

```
Any problem with that or does that sound ok?

**Comment by rbygrave** [comment]
Done now with JsonValueAdapter left out.

**Comment by PR-O** [comment]
Perfect @rbygrave , looking forward to updating to 4.7.2 :smile: ! Thanks for adding this back in so quickly.
