### ISSUE TITLE
java.lang.NoSuchMethodError: com.avaje.ebean.bean.EntityBeanIntercept.preGetter

### ISSUE THREAD

**Issue by jbcpollak** [ebean-orm/avaje-ebeanorm#311]
Hello, I am trying to upgrade my Ebeans installation. Currently we are using 3.3.2 of ebeans, and 3.3.2 of the `avaje-ebeanorm-mavenenhancer`.

When I upgrade the enhancer in the pom.xml to the latest version (4.5.3) I start to get exceptions like this:

`
java.lang.NoSuchMethodError: com.avaje.ebean.bean.EntityBeanIntercept.preGetter(I)V
	at com.mycompany.beans.MyBean._ebean_get_myLinks(MyBean.java:1)
	at com.mycompany.beans.MyBean._ebean_set_myLinks(MyBean.java:1)
	at com.mycompany.beans.MyBean.<init>(MyBean.java:112)
	at com.mycompany.beans.MyBeanTest.setUp(MyBeanTest.java:19)
`

The `MyBean.myLinks` object is defined like this:

    @PrivateOwned
    @OneToMany(cascade = CascadeType.ALL)
    @JoinColumn(name = "mybean_id",referencedColumnName = "mybean_id")
    @OrderBy("startDate desc")
    private List<MyLink> myLinks;

The (maybe) interesting thing is that the problem only happens when I upgrade the enhancer. It doesn't matter what version of ebeans I use. I've tried the following ebeans versions: 3.3.2, 3.4.2, 4.5.3, and 4.7.2. 

Am I doing something wrong?

**Comment by rbygrave** [comment]
The enhancement changed in 4.x ... so you can't use 3.x enhancement with
Ebean 4.x and you can't use 4.x enhancement with 3.x Ebean.

So you should be using 4.5.3 of the enhancement with say 4.7.2 of Ebean.

Now, you suggesting that isn't working ... I wonder if there is a fresh
compile and enhancement occurring  (the enhancement detects if the beans
are already enhanced and does not redo the enhancement in that case).


Cheers, Rob.

**Comment by jbcpollak** [comment]
Hi Rob,

> you should be using 4.5.3 of the enhancement with say 4.7.2 of Ebean.

Yes, I initially tried this with the same result as above. My command line
was:

mvn clean test

So I believe the enhancement should be running. I turned debugging if the
enhancement on and it appears to run correctly.

On Mon, Jun 22, 2015, 7:27 PM Rob Bygrave <notifications@github.com> wrote:

> The enhancement changed in 4.x ... so you can't use 3.x enhancement with
> Ebean 4.x and you can't use 4.x enhancement with 3.x Ebean.
>
> So you should be using 4.5.3 of the enhancement with say 4.7.2 of Ebean.
>
> Now, you suggesting that isn't working ... I wonder if there is a fresh
> compile and enhancement occurring (the enhancement detects if the beans
> are already enhanced and does not redo the enhancement in that case).
>
>
> Cheers, Rob.
>
>
> On 23 June 2015 at 10:44, Joshua Chaitin-Pollak <notifications@github.com>
> wrote:
>
> > Hello, I am trying to upgrade my Ebeans installation. Currently we are
> > using 3.3.2 of ebeans, and 3.3.2 of the avaje-ebeanorm-mavenenhancer.
> >
> > When I upgrade the enhancer in the pom.xml to the latest version (4.5.3)
> I
> > start to get exceptions like this:
> >
> >
> > java.lang.NoSuchMethodError:
> > com.avaje.ebean.bean.EntityBeanIntercept.preGetter(I)V
> > at com.mycompany.beans.MyBean._ebean_get_myLinks(MyBean.java:1)
> > at com.mycompany.beans.MyBean._ebean_set_myLinks(MyBean.java:1)
> > at com.mycompany.beans.MyBean.<init>(MyBean.java:112)
> > at com.mycompany.beans.MyBeanTest.setUp(MyBeanTest.java:19)
> >
> > The MyBean.myLinks object is defined like this:
> >
> > @PrivateOwned
> > @OneToMany(cascade = CascadeType.ALL)
> > @JoinColumn(name = "mybean_id",referencedColumnName = "mybean_id")
> > @OrderBy("startDate desc")
> > private List<MyLink> myLinks;
> >
> > The (maybe) interesting thing is that the problem only happens when I
> > upgrade the enhancer. It doesn't matter what version of ebeans I use.
> I've
> > tried the following ebeans versions: 3.3.2, 3.4.2, 4.5.3, and 4.7.2.
> >
> > Am I doing something wrong?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ebean-orm/avaje-ebeanorm/issues/311>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ebean-orm/avaje-ebeanorm/issues/311#issuecomment-114301542>
> .
>
-- 
--
Joshua Chaitin-Pollak
Chief Technology Officer
Assured Labor, Inc.
www.assuredlabor.com
www.empleolisto.com.mx
www.trabalhoja.com.br

**Comment by rbygrave** [comment]
Ok so.

java.lang.NoSuchMethodError: com.avaje.ebean.bean.
EntityBeanIntercept.preGetter(I)V

The "I" here is for int and "V" for return void so it's trying to call:

  public void preGetter(int propertyIndex) {

... which is a method on EntityBeanIntercept from 4.x onwards (so 4.7.2)

That suggests to me that you should do a mvn dependency:tree and look for
an additional older version of Ebean (a 3.x version) being pulled in as a
dependency somehow.  Do you want to do that?


Cheers, Rob.

**Comment by jbcpollak** [comment]
Ok, that is a good idea, I'll check that. Thanks.

On Mon, Jun 22, 2015, 9:49 PM Rob Bygrave <notifications@github.com> wrote:

> Ok so.
>
> java.lang.NoSuchMethodError: com.avaje.ebean.bean.
> EntityBeanIntercept.preGetter(I)V
>
> The "I" here is for int and "V" for return void so it's trying to call:
>
> public void preGetter(int propertyIndex) {
>
> ... which is a method on EntityBeanIntercept from 4.x onwards (so 4.7.2)
>
> That suggests to me that you should do a mvn dependency:tree and look for
> an additional older version of Ebean (a 3.x version) being pulled in as a
> dependency somehow. Do you want to do that?
>
>
> Cheers, Rob.
>
>
>
>
>
>
>
>
> On 23 June 2015 at 12:10, Joshua Chaitin-Pollak <notifications@github.com>
> wrote:
>
> > Hi Rob,
> >
> > > you should be using 4.5.3 of the enhancement with say 4.7.2 of Ebean.
> >
> > Yes, I initially tried this with the same result as above. My command
> line
> > was:
> >
> > mvn clean test
> >
> > So I believe the enhancement should be running. I turned debugging if the
> > enhancement on and it appears to run correctly.
> >
> > On Mon, Jun 22, 2015, 7:27 PM Rob Bygrave <notifications@github.com>
> > wrote:
> >
> > > The enhancement changed in 4.x ... so you can't use 3.x enhancement
> with
> > > Ebean 4.x and you can't use 4.x enhancement with 3.x Ebean.
> > >
> > > So you should be using 4.5.3 of the enhancement with say 4.7.2 of
> Ebean.
> > >
> > > Now, you suggesting that isn't working ... I wonder if there is a fresh
> > > compile and enhancement occurring (the enhancement detects if the beans
> > > are already enhanced and does not redo the enhancement in that case).
> > >
> > >
> > > Cheers, Rob.
> > >
> > >
> > > On 23 June 2015 at 10:44, Joshua Chaitin-Pollak <
> > notifications@github.com>
> > > wrote:
> > >
> > > > Hello, I am trying to upgrade my Ebeans installation. Currently we
> are
> > > > using 3.3.2 of ebeans, and 3.3.2 of the avaje-ebeanorm-mavenenhancer.
> > > >
> > > > When I upgrade the enhancer in the pom.xml to the latest version
> > (4.5.3)
> > > I
> > > > start to get exceptions like this:
> > > >
> > > >
> > > > java.lang.NoSuchMethodError:
> > > > com.avaje.ebean.bean.EntityBeanIntercept.preGetter(I)V
> > > > at com.mycompany.beans.MyBean._ebean_get_myLinks(MyBean.java:1)
> > > > at com.mycompany.beans.MyBean._ebean_set_myLinks(MyBean.java:1)
> > > > at com.mycompany.beans.MyBean.<init>(MyBean.java:112)
> > > > at com.mycompany.beans.MyBeanTest.setUp(MyBeanTest.java:19)
> > > >
> > > > The MyBean.myLinks object is defined like this:
> > > >
> > > > @PrivateOwned
> > > > @OneToMany(cascade = CascadeType.ALL)
> > > > @JoinColumn(name = "mybean_id",referencedColumnName = "mybean_id")
> > > > @OrderBy("startDate desc")
> > > > private List<MyLink> myLinks;
> > > >
> > > > The (maybe) interesting thing is that the problem only happens when I
> > > > upgrade the enhancer. It doesn't matter what version of ebeans I use.
> > > I've
> > > > tried the following ebeans versions: 3.3.2, 3.4.2, 4.5.3, and 4.7.2.
> > > >
> > > > Am I doing something wrong?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/ebean-orm/avaje-ebeanorm/issues/311>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ebean-orm/avaje-ebeanorm/issues/311#issuecomment-114301542
> > >
> > > .
> > >
> > --
> > --
> > Joshua Chaitin-Pollak
> > Chief Technology Officer
> > Assured Labor, Inc.
> > www.assuredlabor.com
> > www.empleolisto.com.mx
> > www.trabalhoja.com.br
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ebean-orm/avaje-ebeanorm/issues/311#issuecomment-114309632
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ebean-orm/avaje-ebeanorm/issues/311#issuecomment-114325483>
> .
>
-- 
--
Joshua Chaitin-Pollak
Chief Technology Officer
Assured Labor, Inc.
www.assuredlabor.com
www.empleolisto.com.mx
www.trabalhoja.com.br

**Comment by jbcpollak** [comment]
Hi, you were correct. This problem was caused by our dependency on `avaje-ebeanorm-spring`, version 3.3.1. This seems to be the latest version. Is it still possible to use Ebeans with Spring? I can't find any documentation on how to do that or how to upgrade.

**Comment by rbygrave** [comment]
Yes spring support is still good - I go need to update the
avaje-ebeanorm-spring project though as you point out.  My last spring
project I created a FactoryBean that also loaded properties .... we can
effectively do both now (xml and properties loading) in terms of spring so
that is really the only change I'd look to do to that avaje-ebeanorm-spring
project.

**Comment by jbcpollak** [comment]
So it looks like the spring project is what brings in the older version of ebeans. I'll try excluding it as a dependency from the spring project and try that.

**Comment by rbygrave** [comment]
I think I can close this now.  Reopen if required.
