### ISSUE TITLE
Ability to remove deregister BeanPersistListeners removed

### ISSUE THREAD

**Issue by dajamminyogesh** [ebean-orm/avaje-ebeanorm#312]
In commit 8c12fc762c938cd76e251464c2400e083fdbd813 the ability to deregister BeanPersistListener objects was removed from the baseline.  Now there exists no mechanism to deregister listeners, which can cause exceptions on application shutdown or reload.  Since this is a public method this breaks compatibility with existing source code.

I recommend the addition of the deregister function back to src/main/java/com/avaje/ebeaninternal/server/deploy/BeanDescriptor.java

**Comment by rbygrave** [comment]
Right. I understand your point so yes I'll look to add that back.

BeanDescriptor is exposed via the SPI (rather than the API) via SpiEbeanServer etc so yes it was a case here of over zealous cleanup (my mistake).

Thanks, Rob.
