### ISSUE TITLE
Can not update row.

### ISSUE THREAD

**Issue by caoli5288** [ebean-orm/avaje-ebeanorm#325]
My Class:
```
@Entity
@Table(name="my_class")
public class MyClass {

    @Id
    private int id;

    private String name;

    private long updateDate;

    // getter and setter.......

}
```
My code like this.
```
MyClass mc = new MyClass();
mc.setName("test");
....// other setter.
Ebean.save(mc);    // It works, I can see a new row in database.

mc.setUpdateDate(System.currentTimeMillis());
Ebean.save(mc);   // Not works, throw exception duplicate id.
```
Other code:
```
MyClass mc = Ebean.find(MyClass.class, 1);
mc.setUpdateDate(System.currentTimeMillis());
Ebean.save(mc);     // No throw, but have no effect, no change in the database.
```
Is there any problem with my code?

**Comment by rbygrave** [comment]
Can you include the SQL that is generated and executed?

<logger name="*org.avaje.ebean.SQL*" level="TRACE"/>
<logger name="org.avaje.ebean.TXN" level="TRACE"/>
<logger name="org.avaje.ebean.SUM" level="TRACE"/>

Then it will be obvious what Ebean is doing exactly.


mc.setUpdateDate(System.currentTimeMillis());
Ebean.save(mc);   // Not works, throw exception duplicate id.

This should result in a SQL update statement.

**Comment by rbygrave** [comment]
Ok, closing this for now.  Reopen if needed.
