### ISSUE TITLE
ENH: Add @DbComment with DDL generation of table and column comments

### ISSUE THREAD

**Issue by xxcode-monkey** [ebean-orm/avaje-ebeanorm#365]
using FileWriter may cause messy code when write out
see# com.avaje.ebeaninternal.server.ddl.DdlGenerator.writeFile
maybe should use FileOutputStream to solve this

    /* FileWriter fw = new FileWriter(f);
    try {
      fw.write(fileContent);
      fw.flush();
    } finally {
      fw.close();
    }*/

    FileOutputStream out = null;
    try {
      out = new FileOutputStream(f, false);
      out.write(fileContent.getBytes("UTF-8"));
      out.flush();
    } finally {
      out.close();
    }

**Comment by rbygrave** [comment]
What do you mean by 'messy code'?  Do you mean some problem with UTF8
encoding?

**Comment by xxcode-monkey** [comment]
As below, the COMMENT will be ??? or some other messy code generated , not the UTF8 encoding   
    @Column(columnDefinition = "varchar(30) COMMENT'角色名称'")
    private String name;

**Comment by xxcode-monkey** [comment]
Additionally , Can Ebean provide annotation @Comment to add COMMENT to table gen ,not the current way in the  columnDefinition part

**Comment by icode** [comment]
DB Migration has column comments? @rbygrave

**Comment by rbygrave** [comment]
Yes but they are not used in 'diff'.

**Comment by icode** [comment]
I don't understand for DbMigration, DbMigration how to know the current database versio? I'm not see a dbversion table.
