### ISSUE TITLE
Call to save result in update instead of insert

### ISSUE THREAD

**Issue by valentincocaud** [ebean-orm/avaje-ebeanorm#378]
I'm using Play framework and I have just updated to 2.4.2. But I have a strange behavior since this update.

__PairingCommit.java__ 
```java
@Entity
public class CommitItem extends Model
{
    @Id
    public String epc;
}

@Entity
public class PairingCommit extends Model
{
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long id;

    @OneToMany(cascade = CascadeType.ALL)
    public List<CommitItem> items;
}
```

I use this beans like this in my code
```java
    public static CommitItem create(PairRequest pair, PairingCommit commit)
    {
        commit.refresh();
        CommitItem item = new CommitItem();
        item.epc = pair.epc;

        commit.items.add(item);
        commit.save();
        return item;
    }
```

But I get an OptimisticLock excpetion on saving. I found out that is because the saving of `item` is done with an `update` instead of an `insert`.
`javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[update commit_item set evat_price=?, ivat_price=?, vat=?, discount=?, discount_is_percentage=?, product_product_code=? where epc=?] bind[null]`

And if I try to save `item` before, it complain about unidirectional relationship.
This code was working well before the update. So is it a normal behavior ?

**Comment by valentincocaud** [comment]
Found out this issue. It exactly the same problem but it it seems that is not actually fixed...
https://github.com/ebean-orm/avaje-ebeanorm/issues/167

**Comment by rbygrave** [comment]
No, I very much doubt it is the same issue - that issue has a test case that doesn't fail.

It is more likely that you are missing a mappedBy attribute in your @OneToMany.

Create a test case outside of Play and I'll have a look at the test case.

**Comment by valentincocaud** [comment]
I have cloned the Ebean project to try to make a test but I haven't understand how tests works

**Comment by rbygrave** [comment]
You don't need to clone Ebean per say ... but instead create a small "cut down" application that shows your issue.  Ideally as part of that you create a 'unit test' with assert statements in it that shows exactly which assert fails ... but you don't need to add the asserts in this case as long as your sample application produces the OptimisticLockException.

**Comment by rbygrave** [comment]
I'll close this for now.  Reopen or post to the google group etc.
