### ISSUE TITLE
ENH: Support delete using a Query instance

### ISSUE THREAD

**Issue by greenlaw110** [ebean-orm/avaje-ebeanorm#398]
Since we already have a `Query` instance which could be used to fetch data, there is no reason why we cannot use it to delete data.

This request is to proposal add an method to `EbeanServer`:

```java
<T> void delete(Query<T> query) throws OptimisticLockException;
```

Please refer to the corresponding method `Datastore.delete(Query)`  defined in Morphia (for mongodb): https://rawgit.com/wiki/mongodb/morphia/javadoc/1.0.1/org/mongodb/morphia/Datastore.html#delete(org.mongodb.morphia.query.Query)

**Comment by rbygrave** [comment]
Note that this delete would not be able to throw OptimisticLockException. There is no optimistic concurrency checking on rows deleted this way (just like the existing bulk delete mechanism).

In looking at the referred mongodb api I don't see anything of interest/note there.  Why was it referenced?  Was there anything specific there that is deemed important or interesting that should be noted?

**Comment by rbygrave** [comment]
I'm guessing that mongo was referenced just to add some weight / justification to the enhancement request and nothing more specific than that.

**Comment by greenlaw110** [comment]
precisely! It's just use as an example how Query object could be used to
specify delete action

**Comment by rbygrave** [comment]
Adding to EbeanServer
```java
  /**
   * Execute as a delete query deleting the 'root level' beans that match the predicates
   * in the query.
   * <p>
   * Note that if the query includes joins then the generated delete statement may not be
   * optimal depending on the database platform.
   * </p>
   *
   * @param query       the query used for the delete
   * @param transaction the transaction to use (can be null)
   * @param <T>         the type of entity bean to fetch.
   * @return the number of beans/rows that were deleted
   */
  <T> int delete(Query<T> query, Transaction transaction);
```

Adding to Query and ExpressionList:
```java
  /**
   * Execute as a delete query deleting the 'root level' beans that match the predicates
   * in the query.
   * <p>
   * Note that if the query includes joins then the generated delete statement may not be
   * optimal depending on the database platform.
   * </p>
   *
   * @return the number of beans/rows that were deleted.
   */
  int delete();
```

**Comment by greenlaw110** [comment]
awesome! This is gonna save me a lot of effort on
https://github.com/actframework/act-ebean project
