### ISSUE TITLE
Turn off lazy loading

### ISSUE THREAD

**Issue by jwaterloo** [ebean-orm/avaje-ebeanorm#400]
Is there a way to turn off lazy loading all together in the configuration?

**Comment by rbygrave** [comment]
No there is not.

**Comment by rbygrave** [comment]
May as well close this then?  Re-open if desired.

**Comment by jwaterloo** [comment]
Thanks for providing setDisableLazyLoading(true) in 6.2.2. Per query is not only acceptable but also preferable. Though both, the other as a configurable default with its on by default for compatibility would be nice.
