### ISSUE TITLE
OffsetDateTime turns into "timestamp without time zone"

### ISSUE THREAD

**Issue by Lugribossk** [ebean-orm/avaje-ebeanorm#402]
When generating DDL for a class with an OffsetDateTime property, it is given the type ```timestamp```, which Postgres interprets as ```timestamp without time zone```. Since it's explicitly a type with timezone information that should be reflected in the database type.

E.g.:
```
@Entity
public class Example {
    private OffsetDateTime updated;
}
```
Which gives:
```
create table example (
  updated                   timestamp)
;
```

**Comment by rbygrave** [comment]
I think this is perhaps more a case that 'timestamp with time zone' could be the default for all timestamps in postgres (so not specific to OffsetDateTime).

I'll look at this a bit more in the next few days.

**Comment by rbygrave** [comment]
My testing using 'timestamp with time zone' shows that is makes no difference for any of the java datetime types including OffsetDateTime.

Someone might desire all the timestamp types in PG to be 'timestamp with time zone' ... which could be done by overriding the DbType in the PostgresPlatform for Types.TIMESTAMP.

So I will close this issue. If you want to discuss further etc re-open this issue.

Thanks, Rob.

**Comment by saliljnr** [comment]
Don't know if this is relevant to your questions but tried annotating the date property field with @Column(columnDefinition = "timestamp with time zone")?

**Comment by rbygrave** [comment]
Thanks, yes that is an option. My take on it is that more likely that if a DBA wanted timestamp with time zone ... that they would want it on all timestamp columns (this is not specific to OffsetDateTime) and in that case you'd look to modify the type in the PostgresPlatform.

That is, personally I would be not using "timestamp with time zone" for just our OffsetDateTime types (I'd be surprised if a Postgres DBA pushed for that case and instead I expect them to push for the "all timestamps should be timestamp with time zone" case).
