### ISSUE TITLE
how to support ebean multiple databases

### ISSUE THREAD

**Issue by vodcms** [ebean-orm/avaje-ebeanorm#409]
how to support ebean multiple databases

**Comment by rbygrave** [comment]
Generally speaking questions are expected to go to the ebean google group. In that way the question is viewed and potentially answered by more people.  Is there a reason you didn't post the question there?

> how to support ebean multiple databases

In ebean.properties specify multitple databases
```properties


datasource.hr.username=hr
datasource.hr.password=hr
datasource.hr.databaseUrl=jdbc:postgresql://127.0.0.1:5432/hr
datasource.hr.databaseDriver=org.postgresql.Driver

datasource.unit.username=unit
datasource.unit.password=unit
datasource.unit.databaseUrl=jdbc:postgresql://127.0.0.1:5432/unit
datasource.unit.databaseDriver=org.postgresql.Driver

```

You can use the names "hr" and "unit" to get the server.
```java

EbeanServer server = Ebean.getServer("hr");

EbeanServer server = Ebean.getServer("unit");

```

**Comment by vodcms** [comment]
thank you @rbygrave  how to enabled in springboot ? pls help me.

**Comment by rbygrave** [comment]
I have not used spring boot yet. Best to ask the question to the google group I'd say.
