### ISSUE TITLE
Require findPagedList() query to specify an order by clause - throw exception if no order by supplied

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#410]
That is, in general paging queries require order by in order to function properly.  Currently Ebean allows the query to execute without an order by and in some cases this results in a non-intuitive error message.

This change would mean findPagedList() must have an order by clause and Ebean will throw an exception if it does not.

**Comment by joe776** [comment]
Just a quick suggestion as I just stumbled over this ticket: what about (maybe always) adding an orderBy on the ID column? This wouldn't throw an exception for existing (bad) code, and its good pratice to have an orderBy on a unique column to break ties, anyway.

**Comment by rbygrave** [comment]
> This wouldn't throw an exception for existing (bad) code

Yes. Throwing the exception is not particularly friendly and someone will no doubt get caught by it at the most inconvenient time (Murphies law).

Order by id it is.  So, if there is not an existing order by clause Ebean will add an order by id. Sounds good - thanks.

**Comment by rbygrave** [comment]
So the change in behavior is that if a query has maxRows > 1 or firstRows > 0 then the query is deemed to be a "paging query". In these cases Ebean will check the existing order by clause to see if it contains the id property.  If the id property is not already in the order by clause it is appended to the end of the order by clause.

This means this behavior applies to both findPagedList() and findList() and findSet() etc. (Applies to any query that has set maxRows > 1 or firstRows > 0).
