### ISSUE TITLE
Extra instance of root level bean with findIterate() and fetch of OneToMany relationship - Ebean parses the first bean correctly and the rest not 

### ISSUE THREAD

**Issue by archie-sh** [ebean-orm/avaje-ebeanorm#425]
If there are 2 customers ie. customer 1 and customer 2 and .fetch("orders") is used then the output would be the following 

Customer id 1
--> Order id 1
--> Order id 3
--> Order id 4
Customer id 2
--> Order id 2
Customer id 2
--> Order id 5

where it should be 

Customer id 1
--> Order id 1
--> Order id 3
--> Order id 4
Customer id 2
--> Order id 2
--> Order id 5

**Comment by michaelsiebers** [comment]
+1

**Comment by bond211** [comment]
+1

**Comment by anteoc** [comment]
+1

**Comment by naemar** [comment]
+1

**Comment by rbygrave** [comment]
@naemar why +1 a closed issue?

**Comment by naemar** [comment]
ah sorry, left the tab open without pressing comment - no worries

**Comment by rbygrave** [comment]
Cool. I was wondering if that +1 meant something like ... "can I have this released soon".  I'll release in the next day or so BTW.
