### ISSUE TITLE
When I get a connection, do I need to manually close it?

### ISSUE THREAD

**Issue by caoli5288** [ebean-orm/avaje-ebeanorm#428]
Sometimes I need to get a JDBC connection to do something.
```
Transaction transaction = Ebean.beginTransaction();
Connection connection = transaction.getConnection();
...

```
Do I need to manually execute the connection's close() call?
I'm sorry I didn't see a clear description about that on the document and javadoc.

**Comment by dastultz** [comment]
On Wed, Sep 30, 2015 at 12:31 PM, Zhang <notifications@github.com> wrote:

> Sometimes I need to get a JDBC connection to do something.
>
> Transaction transaction = Ebean.beginTransaction();
> Connection connection = transaction.getConnection();
> ...
>
>
> Do I need to manually execute the connection's close() call?
> I'm sorry I didn't see a clear description about that on the document and
> javadoc.
>
No, it's just a convenience reference, Ebean will close it at the end of
the transaction. (You DO need to end the transaction with a
commit/rollback/end.

/Daryl

**Comment by rbygrave** [comment]
Daryl has answered this question so I'll close this.  Reopen if necessary.

Thanks, Rob.

**Comment by caoli5288** [comment]
Thanks, now I know do not need call connection's close method. What about statement's ?

**Comment by dastultz** [comment]
On Wed, Sep 30, 2015 at 2:45 PM, Zhang <notifications@github.com> wrote:

> Thanks, now I know do not need call connection's close method. What about
> statement's ?
>

I suppose that might depend on your database. Ebean won't close them for
you. I'd say you should close statements and result sets.

/Daryl

**Comment by caoli5288** [comment]
@dastultz THX！
