### ISSUE TITLE
ENH: Support for UUID mapping to native DB UUID type (Postgres, H2)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#430]
Currently UUID can be mapped to varchar(40) or binary(16).  For databases that have a native UUID type (Postgres, H2) add support for using these types.

This gives storage benefits without the downside of using db type binary(16).

**Comment by santiagomera** [comment]
Hi Rob, I'm getting the following error when trying to use Postgres with native UUID type:
`ERROR:  operator does not exist: uuid = character varying at character 113`

Is it possible you're missing this line https://github.com/ebean-orm/avaje-ebeanorm/blob/master/src/main/java/com/avaje/ebean/config/dbplatform/H2Platform.java#L19 on PostgresPlatform.java ?

**Comment by rbygrave** [comment]
Yes, quite right thanks.  I'll look to fix that up this afternoon.
