### ISSUE TITLE
mysql DDL error

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#433]
```
[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) not null,
  update_time                   datetime(6) not null,
  constrai' at line 11
```

mysql version 5.6.25

**Comment by rbygrave** [comment]
You can either look to upgrade your mysql version or create your own version of MySqlPlatform.  Your choice.

**Comment by icode** [comment]
not support mysql version 5.6.25?

**Comment by rbygrave** [comment]
I presumed that the datatype change between the MySql versions from datetime to datetime(6) is the issue?  I thought that change was in 5.6.4.  Maybe you should confirm exactly what the issue is.
