### ISSUE TITLE
Does Ebean ready to be deployed in OSGi?

### ISSUE THREAD

**Issue by akvyalkov** [ebean-orm/avaje-ebeanorm#434]
Hello. I can't deploy Ebean to Apache Karaf.
It seems that *MANIFEST.MF* is out of date.
Problems starts from slf4j. In your manifest: 
```
Require-Bundle: 
 org.slf4j.api;bundle-version="1.7.2",
```
But there are no *org.slf4j.api* bundles or packages in repos.

**Comment by rbygrave** [comment]
Are you able to update the MANIFEST.MF and make a pull request?

**Comment by akvyalkov** [comment]
Yes. I'll do it in the near future
