### ISSUE TITLE
@EnumValue("01") stored as integer rather than string - ENum stores strings as numerics?

### ISSUE THREAD

**Issue by tbee** [ebean-orm/avaje-ebeanorm#439]
We have an enum with the following style of notations: @EnumValue("01"), note the preceding "0". When stored in the database this values turns into a "1" (varchar field), but EBean correctly handles this.

However, we are now forced to abandon the ENum and switch to strings. This causes problems, because the enum.fromCode(s) now returns a null. We can easily patch this with a SQL statement, but it seems wrong to store "1" instead of "01".

**Comment by vodcms** [comment]
you cann like 

    @Enumerated(EnumType.STRING)
    @Column(name="status",nullable=false)
    private Status status;

**Comment by tbee** [comment]
Hm. I see that this is standard JPA annotation and it stores the name of the enum, which in our case is not the same as the @EnumValue. So that is not correct?

But I also found that the reported behavior is actually documented in EBeans EnumValue: if all enum values can be parsed as integer, ebean will store them as integers... https://ebean-orm.github.io/apidocs/com/avaje/ebean/annotation/EnumValue.html

This, I believe, is very bad automagical behavior. If anything, then enums should have a @Enum(type=Integer) kind of annotation.

**Comment by rbygrave** [comment]
*> if all enum values can be parsed as integer,*

It could be that this is considered a bug.  That "01" should not be
considered an integer.  That is how I'd see it at the moment - that Ebean
is determining that "01" is an integer and that actually it should not (and
that should be considered a bug in Ebean).

**Comment by tbee** [comment]
I believe automatic type determination should not be done in any case. After all, Java is strongly typed, and so should EBean behave. The user should let it know how to behave.

**Comment by tbee** [comment]
The better word would be "explicitly typed". Maybe reuse @Enumerated(EnumType.STRING) to specify the type at the enum?

**Comment by vodcms** [comment]
yes, or use 
```
@enumvalue("enabled")
enabled,
@enumvalue("disabled")
disabled
```

**Comment by rbygrave** [comment]
I think I'll do 2 things:

1 - change the existing parsing check such that "01" is not seen as an integer

2 - Add a new annotation (like @DbEnumValue) that can be put onto a method of the enum where the method returns the value the enum should be stored as into the DB.  That new annotation could have an attribute to indicate if it is a STRING or INTEGER value.

Note: a related JPA JIRA ticket on enum mapping is  https://java.net/jira/browse/JPA_SPEC-47

**Comment by rbygrave** [comment]
Logged #443
