### ISSUE TITLE
ManyToOne query Error getting BeanDescriptor for path 

### ISSUE THREAD

**Issue by vodcms** [ebean-orm/avaje-ebeanorm#440]
```
class Order extends Model{
      @Id
      @GeneratedValue(strategy = GenerationType.AUTO)
      Long id;
      Long userId;
     @ManyToOne
     @JoinColumn(name = "user_id", referencedColumnName = "id", insertable = false, updatable = false)
     List<User> users;
}
class User extends Model{
      @Id
      @GeneratedValue(strategy = GenerationType.AUTO)
      Long id;
      String name;
}
```

i use 
 Ebean.find(User.class).fetch("order").where().findList();

print error like this

java.lang.RuntimeException: Error getting BeanDescriptor for path

pls help me fix it

**Comment by rbygrave** [comment]
There is no "order" property on the User entity bean.

**Comment by vodcms** [comment]
tks how too ad order property?

**Comment by rbygrave** [comment]
It is a standard @OneToMany / @ManyToOne relationship pair. Review the examples - Order / Customer relationship:

https://github.com/ebean-orm/avaje-ebeanorm-examples/blob/master/a-basic/src/main/java/org/example/domain/Order.java

https://github.com/ebean-orm/avaje-ebeanorm-examples/blob/master/a-basic/src/main/java/org/example/domain/Customer.java
