### ISSUE TITLE
@JsonIgnore / @Expose ... not working on @OneToMany or @ManyToMany - was - @Transient field on @MappedSuperclass is not ignored by toJson()

### ISSUE THREAD

**Issue by jsh0** [ebean-orm/avaje-ebeanorm#442]
When I understand #318 correctly, the wanted behavior of `toJson()` ist that it ignores `@Transient` fields. However this does not work if `@Transient` is used on a mapped superclass. Is this wanted or a bug?

To test this, create this two files and run the `main()` contained in `JsonIgnoreTest`.

JsonIgnoreTest.java:
	
	import java.io.File;
	import java.util.ArrayList;
	import java.util.List;
	
	import javax.persistence.Id;
	import javax.persistence.MappedSuperclass;
	import javax.persistence.Transient;
	
	import com.avaje.ebean.Ebean;
	import com.avaje.ebean.EbeanServerFactory;
	import com.avaje.ebean.Transaction;
	import com.avaje.ebean.config.DataSourceConfig;
	import com.avaje.ebean.config.ServerConfig;
	
	@MappedSuperclass
	public class JsonIgnoreTest {
		
		@Id
		private long id;
		
		@Transient
		private List<String> fileNames;
		
		public JsonIgnoreTest() {
			fileNames = new ArrayList<>();
		}
		
		public static void main(String[] args) {
			String databaseName = "test";
			
			DataSourceConfig ds = new DataSourceConfig();
			ds.setUsername("sa");
			ds.setPassword("");
			ds.setUrl("jdbc:h2:./data/" + databaseName + ";DB_CLOSE_DELAY=-1");
			ds.setDriver("org.h2.Driver");
			ds.setMinConnections(1);
			ds.setMaxConnections(25);
			ds.setHeartbeatSql("select 1");
			ds.setIsolationLevel(Transaction.READ_COMMITTED);
			
			ServerConfig config = new ServerConfig();
			config.setName(databaseName);
			config.setDataSourceConfig(ds);
			config.setDefaultServer(true);
			
			config.setDdlGenerate(true);
			config.setDdlRun(!new File("./data/" + databaseName + ".mv.db").exists());
			
			EbeanServerFactory.create(config);
			
			System.out.println(Ebean.json().toJson(new Child()));
		}
		
	}

Child.java:
	
	import java.util.List;
	
	import javax.persistence.Entity;
	import javax.persistence.Transient;
	
	@Entity
	public class Child extends JsonIgnoreTest {
		
		@Transient
		private List<String> fileNames2;
		
	}

The Code returns `{"fileNames":[]}`, but `fileNames` is annotated `@Transient`

If this behavior is wanted, I would like ask for an alternative. `@JsonIgnore` is also not working.

**Comment by rbygrave** [comment]
You should be able to use Ebean's @JsonIgnore or @Expose.  No, @Transient is not expected to be sufficient (although I understand that is confusing).

**Comment by jsh0** [comment]
`@JsonIgnore` and `@Expose(deserialize = false, serialize = false)` is also not working. Output is still `{"fileNames":[]}`.
