### ISSUE TITLE
ENH: Enum mapping - Add annotation @DbEnumValue that can be used to on a enum method which provides DB values

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#443]
Reference https://java.net/jira/browse/JPA_SPEC-47

Example:

```java

public enum Language {
  ENGLISH_US("en-US"),
  ENGLISH_BRITISH("en-BR"),
  FRENCH("fr"),
  FRENCH_CANADIAN("fr-CA");

  private String code;

  Language(String code) {
    this.code = code;
  }
  
  /**
   * This method supplies the values the enum is mapped to in the DB.
   */
  @DbEnumValue
  public String getCode() {
    return code;
  }

}

```

**Comment by tbee** [comment]
Ok. Something is fishy in relation to this. I just upgraded to 6.1.10 from the latest 4 and our tests are failing:

java.lang.IllegalArgumentException: Bean value for 12 not found in {016=CTG_TARIFFLIST, 012=PARAMEDICAL, 990=BILATERAL_AGREEMENTS}
at com.avaje.ebeaninternal.server.type.EnumToDbValueMap.getBeanValue(EnumToDbValueMap.java:123)
at com.avaje.ebeaninternal.server.type.EnumToDbStringMap.read(EnumToDbStringMap.java:40)
at com.avaje.ebeaninternal.server.type.ScalarTypeEnumWithMapping.read(ScalarTypeEnumWithMapping.java:71)
at com.avaje.ebeaninternal.server.deploy.BeanProperty.read(BeanProperty.java:539)
at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:74)
... 56 more

The enum:
    @EnumValue("012")    PARAMEDICAL(AanduidingPrestatiecodelijst.PRESTATIECODELIJST_PARAMEDISCHE_HULP_COD192_VEK2_012),
    @EnumValue("016")
    CTG_TARIFFLIST(AanduidingPrestatiecodelijst.NZA_TARIEFLIJST_INSTELLINGEN_016),
    @EnumValue("990")
    BILATERAL_AGREEMENTS("990", "Bilaterale afspraken invullen");

**Comment by tbee** [comment]
Ok. If I let the system reinitialize (recreate the records) with the new version of EBean, the value "012" is written in the database. Not "12". This issue has not been implemented and committed yet, has it?

**Comment by tbee** [comment]
I'm sorry, yes, 6.10.1 has the preceding zero behavior

**Comment by rbygrave** [comment]
Yes - this is https://github.com/ebean-orm/avaje-ebeanorm/issues/439
