### ISSUE TITLE
Spring Boot classpath scanning not finding entity beans

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#444]
In the logs you see:
ClassPathSearch WARN : No Entities found in ClassPath using ClassPathReader 

Spring boot runnable jar has a slightly different classpath entry and Ebean is not handling that correctly.

**Comment by wilkinsona** [comment]
I was made aware of this issue via [this Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/4310). It should be possible to scan the classpath of a Spring Boot executable jar without having to use any Spring Boot-specific code. The rough pattern is that you get hold of all of the URLs from the ClassLoader and then open a connection to each of them. These will (typically) be JarURLConnections from which you can then get the underlying jar file and then process its entries looking for classes that match your search criteria. If you'd like to move away from the Spring Boot-specific logic and would like some help to do so, please let me know.

**Comment by rbygrave** [comment]
Thanks Andy.

> Spring Boot executable jar without having to use any Spring Boot-specific code

Yes. That would be good.

> The rough pattern is that you get hold of all of the URLs from the ClassLoader and then open a connection to each of them. These will (typically) be JarURLConnections from which you can then

Ah right.  I'll look into having a go at that in a few days and let you know how that goes (and ask for help if I get stuck).

Cheers, Rob.
