### ISSUE TITLE
Multiple @*ToMany relations referencing the same type

### ISSUE THREAD

**Issue by maherm** [ebean-orm/avaje-ebeanorm#445]
If there are multiple *ToMany relations referencing the same type in an Entity, Ebean mixes those together.

Consider the following setup:

File: Mail.java
```java
@Entity
public class Mail {
	@Id	@GeneratedValue	private int id;
	private String subject;
	private String body;

        //Getters and Setters
        ...
}
```

File: User.java
```java
@Entity
public class User {
	@Id	@GeneratedValue	int id;
	
	@ManyToMany (cascade ={CascadeType.ALL})
	private List<Mail> inbox;
	@ManyToMany (cascade ={CascadeType.ALL})
	private List<Mail> outbox;

        //Getters and Setters
        ...
}
```

File: ebean.properties
```ini
# generate DDL files
ebean.ddl.generate=true
# run ddl drops and recreates tables
ebean.ddl.run=true

ebean.uuidStoreAsBinary=true
ebean.databaseSequenceBatchSize=1

ebean.debug.sql=true
ebean.debug.lazyload=false

datasource.default=h2
datasource.h2.username=sa
datasource.h2.password=
datasource.h2.databaseUrl=jdbc:h2:mem:test
datasource.h2.databaseDriver=org.h2.Driver
```

File: EbeanToManyTest .java
```java
public class EbeanToManyTest {
	
	@Test
	public void test(){ 
		ServerConfig config = new ServerConfig();
		config.setName("h2");
		config.setDefaultServer(true);
		config.loadFromProperties();
		EbeanServerFactory.create(config); 
		
		User u = new User();
		
		Mail m1 = new Mail();
		m1.setSubject("m1Subject");
		m1.setBody("m1Body");
		
		u.getInbox().add(m1);
		Ebean.save(u);
		
		u = Ebean.find(User.class, u.getId());

		assertEquals(1, u.getInbox().size());
		assertEquals(0, u.getOutbox().size());
	}
}
```

The test fails with the following Output:
```
java.lang.AssertionError: expected:<0> but was:<1>
	at EbeanToManyTest.test(EbeanToManyTest.java:34)
```

Generated h2-create-all.sql
```sql
create table mail (
  id                            integer not null,
  subject                       varchar(255),
  body                          varchar(255),
  constraint pk_mail primary key (id)
);
create sequence mail_seq;

create table user (
  id                            integer not null,
  constraint pk_user primary key (id)
);
create sequence user_seq;

create table user_mail (
  user_id                       integer not null,
  mail_id                       integer not null,
  constraint pk_user_mail primary key (user_id,mail_id)
);

alter table user_mail add constraint fk_user_mail_user foreign key (user_id) references user (id) on delete restrict on update restrict;
create index ix_user_mail_user on user_mail (user_id);

alter table user_mail add constraint fk_user_mail_mail foreign key (mail_id) references mail (id) on delete restrict on update restrict;
create index ix_user_mail_mail on user_mail (mail_id);
```

As you can see, Ebean creates one join table USER_MAIL for both relations which results in two identic Lists for "inbox" and "outbox" when you load the Entity from the database.

**Comment by maherm** [comment]
The behavious is the same when using @OneToMany instead of @ManyToMany:
Generated SQL:
```sql
create table mail (
  id                            integer not null,
  user_id                       integer not null,
  subject                       varchar(255),
  body                          varchar(255),
  constraint pk_mail primary key (id)
);
create sequence mail_seq;

create table user (
  id                            integer not null,
  constraint pk_user primary key (id)
);
create sequence user_seq;

alter table mail add constraint fk_mail_user_id foreign key (user_id) references user (id) on delete restrict on update restrict;
create index ix_mail_user_id on mail (user_id);
```

**Comment by dastultz** [comment]
On Wed, Oct 28, 2015 at 10:30 AM, maherm <notifications@github.com> wrote:

> If there are multiple *ToMany relations referencing the same type in an
> Entity, Ebean mixes those together.
>

You are allowing Ebean to decide how to join. You need to specify it.
Here's an example of how I join a User to a collection of Role:

@ManyToMany(cascade = CascadeType.PERSIST)
@JoinTable(name = "userroles",
joinColumns = { @JoinColumn(name = "userid", referencedColumnName =
"userid") },
inverseJoinColumns = { @JoinColumn(name = "roleid", referencedColumnName =
"roleid") }
)
private Set<Role> validRoles;

Notice I specify the table name to join on "userroles". (Primary keys are
Users.userId and Roles.roleId.)

/Daryl

**Comment by maherm** [comment]
Thanks! Nevertheless, I would expect that the ORM takes care of something like that when it generates the schema. Or at least warns the user somehow, for example by throwing an exception at enhancement or at runtime. I can not think of any use case when this behaviour may be intended.

**Comment by dastultz** [comment]
On Wed, Oct 28, 2015 at 11:49 AM, maherm <notifications@github.com> wrote:

> Thanks! Nevertheless, I would expect that the ORM takes care of something
> like that when it generates the schema. Or at least warns the user somehow,
> for example by throwing an exception at enhancement or at runtime. I can
> not think of any use case when this behaviour may be intended.
>

I would say it's a problem with the default DDL generation not being
granular enough. If the default join table name included the field name
(inbox_user_mail, outbox_user_mail) it should just work.

/Daryl

**Comment by rbygrave** [comment]
The 'fix' for this is to detect when the ManyToMany intersection table is not unique and throw an exception ... such that @JoinTable is used to manually specify a good intersection table name.

	at com.avaje.tests.m2m.TestM2MMultipleLists.test(TestM2MMultipleLists.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Property com.avaje.tests.model.m2m.MailUser.outbox has duplicate ManyToMany intersection table mail_user_mail_box. Please use @JoinTable to define unique table to use


For the 'fix' here for TestM2MMultipleLists is to add the @JoinTable annotations like:

```java
  @ManyToMany(cascade = CascadeType.ALL)
  @JoinTable(name = "mail_user_inbox")
  List<MailBox> inbox;

  @ManyToMany(cascade = CascadeType.ALL)
  @JoinTable(name = "mail_user_outbox")
  List<MailBox> outbox;
```

**Comment by rbygrave** [comment]
Note that we don't want to change the naming convention as that would be a breaking change that we want to avoid.

**Comment by askell** [comment]
Is there any option to disable this in case of MappedSuperclass usage? E.g. if there is A, B, and C all extends Base, and A and C has the reference to Other class. So there is "base", "other" and "base_other" tables, but ebean 6.18.1 complains that A and C "has duplicate ManyToMany intersection table"

**Comment by rbygrave** [comment]
Why are you not using `@JoinTable` ?   How do you think that should work without using a `@JoinTable` ?

**Comment by alexanderzaripov-qs** [comment]
> Why are you not using `@JoinTable` ? How do you think that should work without using a `@JoinTable` ?

Previously (since Play 2.1) we was not using `@JoinTable` and relying on defaults (there was needed single "base_other" join table). So now, when migrating to play 2.5 and new ebean, we need to manually introduce separate join tables, like "a_other", "b_other" and write inconvenient migrations

**Comment by askell** [comment]
> Why are you not using `@JoinTable` ? How do you think that should work without using a `@JoinTable` ?

Previously (since Play 2.1) we was not using @JoinTable and relying on defaults (it succesfully used single "base_other" join table). So now, when migrating to play 2.5 and new ebean, we need to manually introduce separate join tables, like "a_other", "b_other" and write inconvenient migrations

**Comment by rbygrave** [comment]
Ok, I understand.
