### ISSUE TITLE
Support exclude model for generate DDL

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#452]
I have some models for already db table, so i don't want generate drop/create table DDL.
But i use them models on ebean server

**Comment by rbygrave** [comment]
I don't see the value in this scenario yet.  For example, when running tests with something like H2 you always want to drop/create all the tables.  When you are testing against another DB ... is the create table not a one off occurrence?   If it is one off then this really comes into the use of DB Migration which does this (produces a diff of the DDL as the model evolves over time).

So currently, I don't understand the scenario / value ... perhaps you can explain more.

**Comment by rbygrave** [comment]
I'll close this for now.  Re-open when you have more explanation of the scenario and value this brings.
