### ISSUE TITLE
Have SQL Injection filter?

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#453]
All method has SQL Injection check？

**Comment by dastultz** [comment]
Ebean uses prepared statements. It's not so much a "check" but a "prevention". https://www.owasp.org/index.php/Preventing_SQL_Injection_in_Java

Also, it appears you are using the issue tracker here for discussion. There is a Google Group: 
https://groups.google.com/forum/#!forum/ebean
I'd like to suggest you ask questions there and use the issue tracker for bug reports and feature requests.
