### ISSUE TITLE
When fetching, collections can get populated with too many entities

### ISSUE THREAD

**Issue by pieterbos** [ebean-orm/avaje-ebeanorm#462]
We have the following entity models:

One Survey has many categories
One Category has many groups
One Group has many questions

In our example, we have:

One survey
One Category
two Groups
Each group has two questions

Now when we do

```java
Survey survey = Ebean.find(Survey.class)
   .fetch("categories")
   .fetch("categories.groups")
   .fetch("categories.groups.questions")
   ....
   .findUnique();
```

We get:
One survey
One Category
Four groups
Each group has two questions

The groups list in category contains the first group twice, then the second group twice - the same java objects with the same memory reference.

I haven't had time to create a small application that reproduces and tests this. but snippets from our models:

Survey.java:
```java
    @OneToMany(mappedBy = "survey", cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @OrderBy("sequenceNumber")
    private List<Category> categories;
```

Category.java:
```java
    @ManyToOne
    @JoinColumn(name = "surveyObjectId")
    private Survey survey;

    @OneToMany(mappedBy = "category", cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @OrderBy("sequenceNumber")
    private List<Group> groups;
```

Group.java:
```java
    @ManyToOne
    @JoinColumn(name = "categoryObjectId")
    private Category category;

    @OneToMany(mappedBy = "group", cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @OrderBy("sequenceNumber")
    private List<Question> questions = new ArrayList<>();
```

Question.java:
```java
    @ManyToOne
    @JoinColumn(name = "groupObjectId")
    private Group group;
```

Reproducible in 6.10.4 and 6.9.1. In Ebean version 4.5.5 it works fine. It prevents us from upgrading to a newer version than 4.5.5.

**Comment by rbygrave** [comment]
Ping back when you have a test case.

**Comment by rbygrave** [comment]
Any luck getting an example test case ?

**Comment by pieterbos** [comment]
Things have been a bit busy lately. I'll try to see if I can find someone to work on a test-case this week.

**Comment by pieterbos** [comment]
@rbygrave See this pull request for a test that reproduced the issue

https://github.com/ebean-orm/avaje-ebeanorm/pull/560

Removing the @OrderBy annotations does not fix the test.
If i cherry-pick the test commit on the avaje-ebeanorm-4.5.5 branch the test succeeds.

**Comment by rbygrave** [comment]
Thanks for the test case, I appreciate it.  
Cheers, Rob.

**Comment by jtammen** [comment]
I am getting hit by the same problem and I am stuck to Play 2.4.6 and thus Ebean < 6.15 (see https://github.com/playframework/play-ebean/issues/69) @rbygrave Is there any way to work around this problem without updating to 6.17.3?

**Comment by rbygrave** [comment]
We can discuss this on the Ebean Google group forum if you wish.
