### ISSUE TITLE
Ebean run jar error is NOT an Entity Bean registered with this server

### ISSUE THREAD

**Issue by vodcms** [ebean-orm/avaje-ebeanorm#468]
i use maven build java jar app. buu run it on java  wrapper services  has error like this

javax.persistence.PersistenceException: Model.MonUser is NOT an Entity Bean registered with this server?

No Entities found in ClassPath using ClassPathReader [com.avaje.ebeaninternal.server.util.DefaultClassPathReader@7674c011] Classpath Searched[[file:/opt/eagle/lib/wrapper.jar, file:/opt/eagle/lib/annotations-13.0.jar, file:/opt/eagle/lib/avaje-agentloader-2.1.2.jar, file:/opt/eagle/lib/avaje-ebeanorm-6.10.3.jar, file:/opt/eagle/lib/avaje-ebeanorm-agent-4.7.1.jar, file:/opt/eagle/lib/commons-lang3-3.4.jar, file:/opt/eagle/lib/commons-pool2-2.3.jar, file:/opt/eagle/lib/drc.client-1.0.0.jar, file:/opt/eagle/lib/lib/commons-lang3-3.4.jar, file:/opt/eagle/lib/lib/avaje-ebeanorm-6.10.3.jar, file:/opt/eagle/lib/lib/annotations-13.0.jar, file:/opt/eagle/lib/lib/persistence-api-1.0.jar, file:/opt/eagle/lib/lib/slf4j-api-1.7.7.jar, file:/opt/eagle/lib/lib/jackson-core-2.5.3.jar, file:/opt/eagle/lib/lib/avaje-agentloader-2.1.2.jar, file:/opt/eagle/lib/lib/avaje-ebeanorm-agent-4.7.1.jar, file:/opt/eagle/lib/lib/jedis-2.8.0.jar, file:/opt/eagle/lib/lib/commons-pool2-2.3.jar, file:/opt/eagle/lib/lib/mysql-connector-java-5.1.18.jar, file:/opt/eagle/lib/lib/drc.client-1.0.0.jar, file:/opt/eagle/lib/jackson-core-2.5.3.jar, file:/opt/eagle/lib/jedis-2.8.0.jar, file:/opt/eagle/lib/junit-3.8.1.jar, file:/opt/eagle/lib/mysql-connector-java-5.1.18.jar, file:/opt/eagle/lib/persistence-api-1.0.jar, file:/opt/eagle/lib/lib/commons-lang3-3.4.jar, file:/opt/eagle/lib/lib/avaje-ebeanorm-6.10.3.jar, file:/opt/eagle/lib/lib/annotations-13.0.jar, file:/opt/eagle/lib/lib/persistence-api-1.0.jar, file:/opt/eagle/lib/lib/slf4j-api-1.7.7.jar, file:/opt/eagle/lib/lib/jackson-core-2.5.3.jar, file:/opt/eagle/lib/lib/avaje-agentloader-2.1.2.jar, file:/opt/eagle/lib/lib/avaje-ebeanorm-agent-4.7.1.jar, file:/opt/eagle/lib/lib/jedis-2.8.0.jar, file:/opt/eagle/lib/lib/commons-pool2-2.3.jar, file:/opt/eagle/lib/lib/mysql-connector-java-5.1.18.jar, file:/opt/eagle/lib/lib/drc.client-1.0.0.jar, file:/opt/eagle/lib/slf4j-api-1.7.7.jar]]

**Comment by rbygrave** [comment]
> buu run it on java wrapper services

It is not clear what that means.  Are you building a runnable jar using spring boot or something like that?

> No Entities found in ClassPath using ClassPathReader 

There are 2 configuration settings to control the searching.  The jars that are searched (if the entities are in an included jar) and the packages that are searched.

These 2 options can be set in ebean.properties or via serverConfig.  Are you setting either of these options?

Is the Model.MonUser entity bean in a included jar?  It looks like the package name is Model with an uppercase "M" - that normally isn't the java convention - just pointing that out.

**Comment by vodcms** [comment]
i fix it. must package  exclude ebean jar to one jar.

**Comment by rbygrave** [comment]
Ok, closing it then.

**Comment by yuzerk** [comment]
hello, i just meet the same problem, but i can not understand what is "package exclude ebean jar to one jar", could you teach me ?@vodcms. thanks advance
