### ISSUE TITLE
Casting timestamp to Json

### ISSUE THREAD

**Issue by leantony** [ebean-orm/avaje-ebeanorm#470]
Iam using java ebeans, and loving it. However, am having an issue serializing my timestamp fields (created_at, updated_at), to JSON. Here's my base model class. Followed the example on the docs
Imports and getters/setters have been omitted for brevity
Oh, am using postgres 9.3

```java
@MappedSuperclass
public class BaseModel extends Model {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long id;

    @Version
    @JsonIgnore
    public Long version;

    @CreatedTimestamp
    @Column(name = "created_at")
    @JsonSerialize(using = JsonDateSerializer.class)
    public Timestamp createdAt;

    @UpdatedTimestamp
    @Column(name = "updated_at")
    @JsonSerialize(using = JsonDateSerializer.class)
    public Timestamp updatedAt;
}
```

Here's the JSON serializer class.
```java
public class JsonDateSerializer extends JsonSerializer<Timestamp> {
    private static final DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");

    @Override
    public void serialize(Timestamp timestamp, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException, JsonProcessingException {
        String formattedDate = dateFormat.format(timestamp);
        jsonGenerator.writeString(formattedDate);
    }
}
```
I have even tried adding the following annotation to the timestamp field. But it doesn't work
```java
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm:ss")
```
This is the result i get, after all my efforts.
```json
"category": {
      "id": 1003,
      "name": "Laptops",
      "description": null,
      "createdAt": 1448700039023,
      "updatedAt": 1448700039023
},
```
What could be the problem?

**Comment by rbygrave** [comment]
Are you using ebean's json features to serialise to JSON? if so then you
should look to use the format options available of ServerConfig.

Cheers, Rob.

**Comment by leantony** [comment]
Yes I am. This is how my query looks like
```java
JsonContext context = Category.db().json();
Category category = Category.db().find(Category.class, 1003);
System.out.println(context.toJson(category));
```

**Comment by rbygrave** [comment]
Ebean uses Jackson core and not jackson databind. Hence that annotation has
no effect.

**Comment by leantony** [comment]
Ok, am not familiar with jackson, so How do I then proceed to sort the issue. Are there any references on the docs that can help me get started with json?
Ive read the json portion on the docs, but it doesn't contain that much info

**Comment by leantony** [comment]
After doing abit of digging, i've found a temporary solution
```java
ObjectMapper mapper     = new ObjectMapper();
        try {
            String jsonString = mapper.writeValueAsString(category);
            System.out.println(jsonString); // works !!!
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
```
But then, all fields in the entity are returned. Which may not always be the case. Thanks for your help!!

**Comment by rbygrave** [comment]
Note: For future reference you can use com.avaje.ebean.config.JsonConfig.DateTime.ISO8601 to get ISO8601 formatting of timestamps.

ServerConfig.setJsonDateTime(JsonConfig.DateTime.ISO8601)

or via properties

ebean.jsonDateTime=ISO8601

**Comment by leantony** [comment]
Thanks. I have a question though. Is it possible to place this in the ebeans.properties file?

**Comment by rbygrave** [comment]
As I said above ...

or via properties

ebean.jsonDateTime=ISO8601

**Comment by leantony** [comment]
wow. thank you very much. works like a charm
