### ISSUE TITLE
Sqllite does not support "alter table <table> add constraint"

### ISSUE THREAD

**Issue by benmccann** [ebean-orm/avaje-ebeanorm#471]
Creating a OneToMany relationship using ebean and SQLite fails because ebean generates an `alter table <table> add constraint <name> foreign key..` statement for the n:m matching table. SQLite does not support "alter table add constraint"  as stated [here](https://www.sqlite.org/omitted.html).

**Comment by rbygrave** [comment]
Note: This might be a duplicate of #100.

**Comment by benmccann** [comment]
Yes, it looks like it. I will close this issue
