### ISSUE TITLE
Invalid SQL for generating ID from sequence on DB2

### ISSUE THREAD

**Issue by mightyzero** [ebean-orm/avaje-ebeanorm#490]
In `com.avaje.ebean.config.dbplatform.DB2SequenceIdGenerator` the base SQL is `"select nextval for " + seqName`. If run this exception will be thrown:

`com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=END-OF-STATEMENT;for FOO_BAR_SEQ;<table_expr>, DRIVER=3.69.24`

The correct SQL is `"values nextval for " + seqName`.

**Comment by rbygrave** [comment]
Are you sure?  Seems neither is correct but instead be:

SELECT NEXT VALUE FOR SEQUENCE_COL;

So then it should be:  "select next value for " + seqName;

**Comment by rbygrave** [comment]
Ok, no it looks like what you suggest will work best (I don't have a local
DB2 instance at the moment).

**Comment by mightyzero** [comment]
`SELECT NEXT VALUE FOR SEQUENCE_COL;`
does the same thing. It's still affected by the `select` syntax, which requires a `from TABLE` clause.

**Comment by rbygrave** [comment]
Well, it is in and released to maven central (6.13.3) so you can probably
try it now.

**Comment by mightyzero** [comment]
Yep, it worked. Well done!
