### ISSUE TITLE
Cascade Persist with same name id columns causes column "id" specified more than once

### ISSUE THREAD

**Issue by IvanAR** [ebean-orm/avaje-ebeanorm#495]
When i try to persist a @OneToOne object with cascade where the two classes has the same @Id column name, the ORM throws the following exception:

javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[ERROR: column "id" specified more than once\n   Position: 40]

Person class is:
```java
public class Person {

    @Id
    @GeneratedValue
    private Long id;

    @Column(name = "address")
    @OneToOne(cascade = { CascadeType.ALL })
    private Address address;
    ....
}
```
Address is:
```java
public class Address {

    @Id
    @GeneratedValue
    private Long id;
    ...
}
```
The save is:
```java
Person person = new Person();
person.setId(1L);
person.setName("Gandalf");
person.setSurName("The Gray");
Address address = new Address();
address.setBlock("Everywhere");
address.setStreet("Every street");
address.setNumber(1);
address.setId(1L);
person.setAddress(address);
dao.save(person);
```
The SQL generated is:
[main] DEBUG org.avaje.ebean.SQL - txn[1001] insert into address (id, street, number, block) values (?,?,?,?); --bind(1,Every street,1,Everywhere,)
[main] DEBUG org.avaje.ebean.SUM - txn[1001] Inserted [Address] [1]
[main] DEBUG org.avaje.ebean.SQL - txn[1001] insert into person (id, name, surName, id) values (?,?,?,?); --bind(1,Gandalf,The Gray,1,)
[main] DEBUG org.avaje.ebean.SUM - txn[1001] ERROR executing DML bindLog[1,Gandalf,The Gray,1,] error[ERROR: column "id" specified more than once\n   Position: 40]

**Comment by rbygrave** [comment]
Try @JoinColumn rather than @Column.

**Comment by IvanAR** [comment]
Now it works, Thank you!

**Comment by rbygrave** [comment]
Great.  

I wonder if we should detect this (probably fairly common) mapping situation and throw an exception.  I won't do that for now but someone reading this in the future could raise that option and we could look at it again (detecting this mapping situation and throwing a nice meaningful exception).
