### ISSUE TITLE
PropertyMapLoader has excessive logging

### ISSUE THREAD

**Issue by wsargent** [ebean-orm/avaje-ebeanorm#501]
The default Play logback configuration explicitly disables the PropertyMapLoader because it logs at too high a level:

```
  <!-- Off these ones as they are annoying, and anyway we manage configuration ourselves -->
  <logger name="com.avaje.ebean.config.PropertyMapLoader" level="OFF" />
```

https://github.com/playframework/playframework/blob/master/framework/src/play-logback/src/main/resources/logback-play-default.xml#L34

We were going through the logback configuration and thought to mention it https://github.com/playframework/playframework/pull/5391#discussion_r47827695

Is this something that is still an issue?

**Comment by rbygrave** [comment]
I presume this could be stated as:

'the logging in property map loader currently logs messages at INFO level -
can those be reduced to DEBUG level'

Is that an accurate interpretation?

Thanks, Rob.

**Comment by wsargent** [comment]
Yes, sorry if that wasn't clear.

**Comment by rbygrave** [comment]
No worries.  Looking at PropertyMapLoader the log messages are at DEBUG level (apart from ERROR).

Looking at history:  This probably was 'fixed' in #457 "When ebean.properties does not exist do not log error message" ... which was included in version 6.11.1

So yes, probably fixed in 6.11.1 I'd say.

**Comment by benmccann** [comment]
Thanks @rbygrave. We can probably close this then. I sent a PR to upgrade Play to use a newer version that has the improvement. https://github.com/playframework/play-ebean/pull/68

**Comment by rbygrave** [comment]
Thanks. Closing.
