### ISSUE TITLE
ExpressList.notIn method does not work

### ISSUE THREAD

**Issue by koyabr** [ebean-orm/avaje-ebeanorm#509]
I'm using ebean 6.9.1
The code below 

```
Ebean.find(Task.class).where()
                .notIn("id", taskIds)
                .gt("deadline", new Date())
                .findList();
```
generates a SQL query with a syntax error:

`select ... from task t0 where  and t0.deadline > ?  `

There is a noticeable blank between `where` and `and t0.deadline`.

However using code below works without a problem

```
Ebean.find(Task.class).where()
                .not(Expr.in("id", taskIds))
                .gt("deadline", new Date())
                .findList();
```

**Comment by rbygrave** [comment]
Thanks for this bug report.

**Comment by Zenoo** [comment]
`.notIn("id", taskIds)`

Still doesn't work on ebean 10.3

Just lost a few hours trying to figure out what went wrong when all I had to do is replace it with 

`.not(Expr.in("id", taskIds))`

...

**Comment by rbygrave** [comment]
@Zenoo I presume you know that the latest version of Ebean is 11.22.5.    10.3 is not really a recent version - you could compare the code etc.
