### ISSUE TITLE
db migration support multi file

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#519]
module1.jar has 0.1.0__default.model.xml
module2.jar has 0.1.0__default.model.xml
and more ...

can read all `*.model.xml` file in jar?

**Comment by rbygrave** [comment]
In this case you would have a module specific path ... by setting the migrationPath to be "dbmigration/module1" ... instead of "dbmigration".

**Comment by icode** [comment]
db migration can read file in jar?

**Comment by rbygrave** [comment]
DB migration does not no ... but you might be using FlywayDB or Liquibase
to do exactly that.

DB Migration is currently just scoped to generating the scripts and not
executing them.

**Comment by icode** [comment]
but diif model must be read previous `*.model.xml`

**Comment by icode** [comment]
but diif model must be read previous `*.model.xml`, and  previous `*.model.xml` in a jar module

**Comment by rbygrave** [comment]
DB Migration diff is only generated as part of development ... hence the reading of the model files only occurs on an expanded jar/war.  DB Migration is never generated on a packaged jar/war.
