### ISSUE TITLE
DDL - DB migration diff does not include DDL to add comment

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#522]
can not diff comment, but new field not add comment

**Comment by xxcode-monkey** [comment]
What are you talking about???

**Comment by icode** [comment]
@rbygrave can you add it?

**Comment by rbygrave** [comment]
0In general icode is talking about the DDL DB Migration ( http://ebean-orm.github.io/docs/setup/dbmigration ) ... and specifically that the DDL "diff" that is generated between the current model and the previous model does not take into account database comments (so you might see alter table add column ... but not the associated ddl to add or change the comment).

Generally what I'd like to see in issues raised like this is an explicit description of the scenario. That can then become a test case and we then get that to pass. When the description is vague then either there is a conversation to clarify (which is wasteful of time) or simply a misunderstanding (a different issue is fixed).

In this case I would have liked to have seen something like:

Scenario: new model has a change to the DB comment (but no other change) 
Expectation: I expect to see DDL to update the existing database comment
Observation: There is no DDL statement

Scenario: new model has a new property with an associated DB comment 
Expectation: I expect to see DDL to add the db column and also to add the comment
Observation: There is DDL to add the column but none to add the database comment

Detailing the issue like this makes it clear, and you can see that each scenario is covered by a test case. 

icode, it might be worth considering putting more effort into issue descriptions. This is a public project and people reading issues like these might equate poorly documented issues as an indication of your capability.

**Comment by icode** [comment]
ok, sorry, my english not good. I want DB migration diff include column comment.
