### ISSUE TITLE
Automatic autotune data

### ISSUE THREAD

**Issue by dastultz** [ebean-orm/avaje-ebeanorm#525]
Hi Rob,

A while back we were talking about the new autotune and profiling work. In older Ebean, these 2 concepts were pretty tied together. In our work we run our application for a month or so then serialize the tuning on exit. When we start up for the next month we have all the previous month’s tuning available and any new code paths get added to the tuning data.

According to the discussion we had back in September (here: https://groups.google.com/forum/?hl=en#!searchin/ebean/automatic$20query$20tuning/ebean/PVDY7CT9QJ4/GsDBHBYkAAAJ) these concepts are separate now. The behavior that I need is that the profiling needs to be applied to the tuning during the run of the application. It’s too much for us to prepare and maintain a tuning file some other way and deploy it with the application. I don’t absolutely have to have the serialization (the part where new and diff is merged?) but if we start with nothing I need my production application to get faster over time. You said:

“At the moment it is manual maintenance. What there should be is a flag / property that can be set such that the profileDiff and profileNew are automatically applied to the existing ebean-autotune.xml file ... but I haven't done that yet. This is the one thing that I know needs to be done shortly.”

So this issue is raised to see about getting this done.

Thanks!

**Comment by rbygrave** [comment]
Yes, good. I need to get this done.

**Comment by rbygrave** [comment]
So with this you can specify the frequency in seconds that the profiling will be collected, compared with the current tuning and apply any changes to the tuning (so the tuned queries get progressively smarter at runtime until they are optimal.

```properties
## specify frequency in seconds
ebean.autotune.profilingUpdateFrequency=5
```
When the update runs (every profilingUpdateFrequency seconds) if there are changes (new or diff's to the existing tuned queries) then an "update" xml file is output to the working directory with the set of changes (new query tuning and diff's to existing query tuning).

When the server is shutdown an "all" file will be output to the working directory.  This file can be renamed to "ebean-autotune.xml" (the default tuning file name) and when the server is next started it will load those tuned queries.

**Comment by dastultz** [comment]
Thanks!

**Comment by rbygrave** [comment]
Excellent - we are slowly getting closer to where we want to be :)
