### ISSUE TITLE
findPagedList with @EmbeddedId broken - automatically adds orderby t0.null

### ISSUE THREAD

**Issue by mshillinger** [ebean-orm/avaje-ebeanorm#526]
It looks like #410 automatically added the  @Id field to the orderBy clause when findPagedList is used.  If the table has an @EmbeddedId field instead, invalid sql is generated.  The last column in the "order by" is null.

I have 2 tables set up in a M2M (users & locations). I am connecting them via a join table.  The join table (loc_user) has a compound primary key which is an EmbeddedId.  

When I attempt to get a pagedList of users for a specific location, the following SQL is generated.

select t0.user_id c0, t0.location_id c1, t0.permission c2, t0.display c3  from loc_user t0 left outer join users t1 on t1.user_id = t0.user_id  where (t0.location_id = ?  and lower(t1.user_email) like ? escape'' )  order by t1.user_email, t0.user_id, t0.null limit 5

After reading #410, I assume "t0.null" is supposed to be the @Id field of the table.

I am in the process up upgrading from Play 2.3 to Play 2.4 which bumped the Ebean version for 3.x to 6.8.1.

Is there anyway to force the query not to append the @Id field to the "order by" clause?

Thanks
MikeS

**Comment by rbygrave** [comment]
Yes, the query should have an order by clause ... then Ebean will not try
to add one automatically using the @id property.

So add an order by and it should be good.

**Comment by rbygrave** [comment]
Can you include the entity beans and the orm query that produces this SQL and I will try and reproduce.

Thanks, Rob.

**Comment by mshillinger** [comment]
Rob, 
I have tried executing the query several different ways.  Specifying a single order("colName") statement and using a single orderBy("colName1 ASC, colName2 ASC").  In both cases, a null column is automatically appended.  I will append a test case later today.

Thanks, Mike

**Comment by mshillinger** [comment]
Rob,
GitHub would not allow me to attach an example to this issue.  I uploaded a tarball containing a maven project to google drive.   The share link is:

https://drive.google.com/file/d/0B0XI1GCFgWJka1BhRDFrNkhVclU/view?usp=sharing

Thanks, Mike

**Comment by mshillinger** [comment]
Rob, 
I pulled the 6.8.1 source and modified BeanDescriptor.appendOrderById() so it would not automatically append to orderBy if idProperty.isEmbedded().

````
  public void appendOrderById(SpiQuery<T> query) {
    if (idProperty != null && !idProperty.isEmbedded()) {
      OrderBy<T> orderBy = query.getOrderBy();
      if (orderBy == null || orderBy.isEmpty()) {
        query.order().asc(idProperty.getName());
      } else if (!orderBy.containsProperty(idProperty.getName())){
        query.order().asc(idProperty.getName());
      }
    }
  }
````
This resolved my issue. There don't seem to be any side effects, all Ebean unit tests passed.

**Comment by rbygrave** [comment]
Thanks.  I have reproduced and confirmed the fix.

**Comment by rbygrave** [comment]
Hi Mike, I have a couple of little things I can point out in the test code (places where there are alternatives that are a little nicer to the DB etc).

If you email me I can reply with those little observations/alternatives.  robin.bygrave at gmail dot com.

Cheers, Rob.
