### ISSUE TITLE
AutoTune - On shutdown provide ability to saving profiling without garbage collection

### ISSUE THREAD

**Issue by dastultz** [ebean-orm/avaje-ebeanorm#531]
Hi Rob,

I used to do some sneakyness to write profiling data on shutdown without doing garbage collection (I do GC for unittests since they are often short-run, but GC is too expensive when I shut down my mighty web app that's been running for a month). This doesn't work any more:

```
SpiEbeanServer spi = (SpiEbeanServer) ....getEbeanServer();
DefaultAutoFetchManager dam = (DefaultAutoFetchManager) spi.getAutoFetchManager();
dam.serialize();
```

Can we have a way to collect and save on shutdown but skip garbage collection?

**Comment by rbygrave** [comment]
Currently on shutdown() if the profiling is on (and skipCollectionOnShutdown is false) then the profiling is saved but additionally System.gc() is called via collectProfiling().

There are 2 options that we can do here:
- on shutdown() have a separate setting/flag to control if GC is executed
- expose the method to write the profiling xml file

**Comment by dastultz** [comment]
I presently have my app set up to call a method to write the file, so I'm good with that, but either way would be fine. I suppose my app would be a little cleaner if there was a separate flag for GC control.

Thanks.

**Comment by rbygrave** [comment]
Yes, I want to do both. 

Currently I'm just thinking the existing method names and skipCollectionOnShutdown flag are not that clear (rely on javadoc a bit too much imo).

**Comment by rbygrave** [comment]
Changes:

Rename skipCollectionOnShutdown to  skipGarbageCollectionOnShutdown in AutoTuneConfig
```properties
## skip GC on shutdown
ebean.autoTune.skipGarbageCollectionOnShutdown=true
```

Add skipProfileReportingOnShutdown to AutoTuneConfig
```properties
## skip reporting profiling on shutdown
ebean.autoTune.skipProfileReportingOnShutdown=true
```

```java
// Add reportProfiling() to Autotune API

Ebean.getDefaultServer().getAutoTune().reportProfiling();
```

**Comment by rbygrave** [comment]
Note that the shutdown behavior is now:

```java
  @Override
  public void shutdown() {
    if (profiling) {
      if (!skipGarbageCollectionOnShutdown && !skipProfileReportingOnShutdown) {
        // trigger GC to update profiling information on recently executed queries
        collectProfiling(-1);
      }
      if (!skipProfileReportingOnShutdown) {
        saveProfilingOnShutdown(false);
      }
    }
  }
```
Note that triggering GC only makes sense to execute if reporting is performed.

**Comment by dastultz** [comment]
Looks good, thanks!
