### ISSUE TITLE
SQLException on getGeneratedKeys using MariaDB latest driver

### ISSUE THREAD

**Issue by simongodard** [ebean-orm/avaje-ebeanorm#538]
After updating to the latest MariaDB Connector/J driver (1.3.4), we started seeing the following exception in our logs:

```
java.sql.SQLException: getGeneratedKeys error. Statement.RETURN_GENERATED_KEYS must be precised on connection.prepareStatement(String sql, int autoGeneratedKeys) or statement.executeUpdate(String sql, int autoGeneratedKeys)
        at org.mariadb.jdbc.MariaDbStatement.getGeneratedKeys(MariaDbStatement.java:800) ~[mariadb-java-client-1.3.4.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.getGeneratedKeys(HikariProxyPreparedStatement.java) ~[HikariCP-2.4.3.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.getGeneratedKeys(InsertHandler.java:168) ~[avaje-ebeanorm-6.8.1.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:132) ~[avaje-ebeanorm-6.8.1.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:73) ~[avaje-ebeanorm-6.8.1.jar:na]
```

It seems to be caused by a change in MariaDB driver default behaviour of Returning generated keys. You now have to explicitly indicate to return generated keys when creating the statement. They say that this is matching the JDBC spec: https://mariadb.atlassian.net/browse/CONJ-234 

For now, we have switched to the MySQL Connector/J driver.

**Comment by rbygrave** [comment]
Thanks, I'll look into it.

**Comment by rbygrave** [comment]
So Ebean is using on Connection:

    PreparedStatement prepareStatement(String sql, String columnNames[])

... which explicitly lists the column names for returning the generated keys. This explicit form (rather than just using the one that the Maria jdbc client refers to) is used as some DB's (Postgres from memory) return more columns than just the generated key column (aka the primary key).

We could ask the Maria jdbc client to support the method Ebean is using (They really should I think) or use platform specific calls (less nice).

Hmm.

**Comment by simongodard** [comment]
Hi Rob,

I just had a closer look at MariaDBConnection code to see how they were handling the ```PreparedStatement prepareStatement(String sql, String columnNames[])``` method and was very surprised with what I saw:
![image](https://cloud.githubusercontent.com/assets/6817637/12582535/c11ec058-c40b-11e5-8762-3ea0f31e2a07.png)

They are ignoring the columnNames argument... I think they should support it.

I guess we can close this issue for now, I will use the MySQL Connector/J instead.

**Comment by rbygrave** [comment]
Submitted a pull request for Maria J Connector.
https://github.com/MariaDB/mariadb-connector-j/pull/69

**Comment by rbygrave** [comment]
So yes I think we can close this one on the Ebean side now.
