### ISSUE TITLE
use `` wrap ddl column name

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#539]
current:
```sql
CREATE TABLE migration_info
(
  version VARCHAR(255) PRIMARY KEY NOT NULL,
  model_diff LONGTEXT,
  rollback LONGTEXT,
  apply LONGTEXT,
  drop LONGTEXT,
  name VARCHAR(255),
  database VARCHAR(255)
);
```
change to:
```sql
CREATE TABLE migration_info
(
  `version` VARCHAR(255) PRIMARY KEY NOT NULL,
  `model_diff` LONGTEXT,
  `rollback` LONGTEXT,
  `apply` LONGTEXT,
  `drop` LONGTEXT,
  `name` VARCHAR(255),
  `database` VARCHAR(255)
);
```

**Comment by rbygrave** [comment]
Ebean can already use quoted identifiers on selected column names and table names.  Quoted identifiers are also DB specific - SQL Server uses [ and ] for example.

You need to clarify what exactly you are looking for here and why.  Quoted identifiers once specified will need to be used everywhere so all generated SQL and supplied SQL (for RawSql and SqlQuery etc) ... and in general I highly recommend avoiding quoted identifiers.

If you are pushing for global use of quoted identifiers you will need to reference some DBA articles that define the benefits and support your case etc.

Cheers, Rob.

**Comment by rbygrave** [comment]
I guess I'll close this then.

**Comment by icode** [comment]
using Hibernate 3.5+, try hibernate.globally_quoted_identifiers=true to quote all database identifiers (this is something they added for JPA 2.0, see the secion 2.13 Naming of Database Objects of the spec for the JPA way to activate this if you are using JPA).

**Comment by icode** [comment]
http://docs.jboss.org/hibernate/orm/3.5/api/org/hibernate/cfg/Environment.html#GLOBALLY_QUOTED_IDENTIFIERS
