### ISSUE TITLE
Q: How to use my own JTA Transaction manager with Ebean?

### ISSUE THREAD

**Issue by fandayrockworld** [ebean-orm/avaje-ebeanorm#541]
How can we use Ebean with JTA tx?

I found that
```java
package com.avaje.ebeaninternal.server.transaction;
public class JtaTransactionManager implements ExternalTransactionManager {
...
     /**
     * Initialise this with the Ebean internal transaction manager.
     */
    public void setTransactionManager(Object txnMgr) {
        
        // RB: At this stage not exposing TransactionManager to 
        // the public API and hence the Object type and casting here

        // TransactionManager HERE IS com.avaje.ebeaninternal.server.transaction.TransactionManager NOT javax.transaction.TransactionManager, BUT HOW CAN WE inject a third part TXM that is a javax implement?
        this.transactionManager = (TransactionManager) txnMgr;     
        this.dataSource = transactionManager.getDataSource();
        this.serverName = transactionManager.getServerName();
    }
...
```
`TransactionManager` HERE IS `com.avaje.ebeaninternal.server.transaction.TransactionManager` NOT `javax.transaction.TransactionManager`, BUT HOW CAN WE inject a third part TXM that is a `javax` implementation? (Like `com.atomikos.icatch.jta.UserTransactionManager` in `atomikos` )

**Comment by rbygrave** [comment]
For programmatic configuration use:

    serverConfig.setUseJtaTransactionManager(true);

or via ebean.properties ...

    ebean.useJtaTransactionManager=true



... that should do it.

Cheers, Rob.

**Comment by fandayrockworld** [comment]
It could not (I only test atomikos and under situation of without integration with j2ee container).

If I only set  `useJtaTransactionManager=ture` and do not set `externalTransactionManager` (I want set one but I can not!), it will new a `JtaTransactionManager` instance, and can not inject `com.atomikos.icatch.jta.UserTransactionManager` instance too.

```java
package com.avaje.ebeaninternal.server.core;
public class InternalConfiguration {
  public InternalConfiguration(XmlConfig xmlConfig, ClusterManager clusterManager,
      ServerCacheManager cacheManager, SpiBackgroundExecutor backgroundExecutor,
      ServerConfig serverConfig, BootupClasses bootupClasses, PstmtBatch pstmtBatch) {
...
ExternalTransactionManager externalTransactionManager = serverConfig.getExternalTransactionManager();
    if (externalTransactionManager == null && serverConfig.isUseJtaTransactionManager()) {
      externalTransactionManager = new JtaTransactionManager();
    }
    if (externalTransactionManager != null) {
      externalTransactionManager.setTransactionManager(transactionManager);
      this.transactionScopeManager = new ExternalTransactionScopeManager(transactionManager, externalTransactionManager);
      logger.info("Using Transaction Manager [" + externalTransactionManager.getClass() + "]");
    } else {
      this.transactionScopeManager = new DefaultTransactionScopeManager(transactionManager);
    }
...
}
```

**Comment by rbygrave** [comment]
Then you should look at the avaje-ebeanorm-spring project and provide your own ExternalTransactionManager.

Refer to: https://github.com/ebean-orm/avaje-ebeanorm-spring/blob/master/src/main/java/com/avaje/ebean/springsupport/txn/SpringAwareJdbcTransactionManager.java

**Comment by fandayrockworld** [comment]
It is also use `ebean TransactionManager` but not `javax` in `SpringAwareJdbcTransactionManager`

**Comment by rbygrave** [comment]
As I understand it the built in JtaTransactionManager does not support your use case. Therefore you need to write your own ExternalTransactionManager.  

SpringAwareJdbcTransactionManager and the built in JtaTransactionManager are example implementations of ExternalTransactionManager that you can use for inspiration.

**Comment by fandayrockworld** [comment]
Even I write an ExternalTransactionManager implementation, the `JtaTransactionManager` also cast it to ebean's TransactionManager forced. 
```java
this.transactionManager = (TransactionManager) txnMgr; // here is ebean's txm
```
So, if I wanna use ebean with JTA, my only way is integrate the JTA implementations into j2ee container.

**Comment by rbygrave** [comment]
> cast it to ebean's TransactionManager forced.

Well, you can do what you like in your own ExternalTransactionManager but actually you also will find you need access to Ebean's TransactionManager just like JtaTransactionManager and SpringAwareJdbcTransactionManager.

That is, you generally MUST have access to Ebean's TransactionManager in order to call the notifyOfCommit() and notifyOfRollback() methods.  So yes, your ExternalTransactionManager needs access to Ebean's TransactionManager to make those calls.

> So, if I wanna use ebean with JTA, my only way is integrate the JTA implementations into j2ee container.

No. You do need to write your own ExternalTransactionManager though.  In doing so you will need to hook into the transaction synchronisation events (ala JTA TransactionSynchronizationRegistry and Synchronization).

There is no JEE container for the Spring transaction integration for example and that has the same functional requirements. You do need the same event hooks - JTA TransactionSynchronizationRegistry and Synchronization ... and that is what you will have to figure out (for example, how to get TransactionSynchronizationRegistry).

**Comment by fandayrockworld** [comment]
Thanks Rob, I will do that after deeply study on JTA.

**Comment by rbygrave** [comment]
Ok, closing for now.
