### ISSUE TITLE
ENH: @DbJson fields are auto serialized and deserialized to specified classes.

### ISSUE THREAD

**Issue by ncphillips** [ebean-orm/avaje-ebeanorm#542]
We're using Ebean 4.6.3 in Play 2.4.x

I have a model that is similar to this:
```
@Entity
public class PersonGroup extends Model {
    @DbJsonB
     public Map<String, Person> persons;
}
```

For some reason Ebean doesn't serialize the `Person` objects, but instead stores a string with their memory location.

```
{"0": "models.Person@3ff"}
```

This problem is definitely seems to be happening on the write, because if I manually insert the properly formatted JSON representation of a Person into the database, it successfully deserializes the object into a Person when reading.

Can someone provide some insights into why this isn't working?

**Comment by rbygrave** [comment]
There are a lot of specific ScalarTypes this can map to (Mapping to Database VARCHAR, CLOB, BLOB, Postgres JSON or Postgres JSONB). However, most of those go through the ScalarTypeJsonMap.bind() ... and that method converts the Map into JSON string content.

So run with a debugger and put a break point there ... 

HOWEVER, your Map has Person as a value type and assuming that is a @Entity that is not expected at all.  That is, with @DbJson/@DbJsonB you are expected to put arbitrary JSON and not relationships to other entity beans or bean types but instead JSON compatible types (boolean, long, double, String, and Map's or Lists of json compatible types).

This means it ends up going into EJsonWriter.writeJson() line 83 and doing object.toString() on the person instance.

**Comment by rbygrave** [comment]
The question becomes, why is the model not:

@OneToMany(mappedBy="group")
public List<Person> persons;

rather than:

@DbJsonB
public Map<String, Person> persons;

**Comment by ncphillips** [comment]
Sorry my Person/Person group example wasn't the best choice. In our use case `Person` is not another database entity, it's just a plain old java class.

**Comment by rbygrave** [comment]
Right, so that makes sense but is not supported.

That is, by implication you are expecting Jackson ObjectMapper (or similar) to be used to marshal and unmarshal the Person bean to/from JSON and that is not supported.  You need to use Object (and not Person).

**Comment by ncphillips** [comment]
Hmm okay, so how would I actually do this? How should I be storing a Person in order make sure I get it back as a Person? Is this not supported at all?

**Comment by rbygrave** [comment]
Using a Person bean - no it is not supported as previously stated.  

How are you expected to do it?  As per the javadoc of @DbJsonB - use Object and not Person so in this case Object would be an actual Map instance.  That is, you lose type safety here.  

You can refer to the tests using @DbJson and @DbJsonB  ... TestJsonMapBasic is probably the one to look at. 

We can convert this ticket into an enhancement request but no it is not supported as you are attempting to use it. To state that in a different way, what you are expecting requires Jackson ObjectMapper which is an optional dependency and not Jackson core. What you are expecting is probably to mix structured and unstructured using Jackson ObjectMapper and no that is currently not supported.

**Comment by ncphillips** [comment]
I'll try to figure out a workaround, but in the meantime here's a much more complete description of how I was expecting the @DbJson decorator to work.

*Models:*
```
@Entity
public class Report {
    @DbJsonB
    Map<String, ReportSections> sections;
    
    public Report() {
        sections = new HashMap<>();
    }
}

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME,
		include = JsonTypeInfo.As.PROPERTY,
		property = "type")
@JsonSubTypes({
		@JsonSubTypes.Type(value = TitleSection.class, name="TitleSection"),
		@JsonSubTypes.Type(value = AuthorListSection.class, name="AuthorListSection"),
})
public abstract class ReportSection {
    public String getType();
}

public class TitleSection extends ReportSection {
    String title;

    public String getType() {
        return "TitleSection"; 
    }    

    @Override
    public boolean equals(Object o) {
        if(this == o) 
            return true;

        if(o == null || getClass() != o.getClass()) 
            return false;

        final TitleSection that = (TitleSection)o;
        return Objects.equals(title, that.title);
    }
}

public class AuthorListSection extends ReportSection {
    List<String> authorNames;
    public String getType() { return "AuthorListSection"; }

}

// Maybe some more subclasses...I want to use DbJson so I don't have
// to make a new table for every Section subtype, but I still want the 
// type-safety of using objects.
```

*Controller Method:*

```
public class ReportsApi extends Controller {
    public Results getReport(Long id) {
        Report report = new Model.Finder<Long, Report>().byId(id);
        ok(Json.toJson(report));
    }

     public Results update(Long id) {
       /**
        * Example Json Format
        * { reportSections: { "0": {"type": "TitleSection", "title": "Working title" }}
        */
        JsonNode json = request().body().asJson();

        Report report = new Model.Finder<Long, Report>().byId(id);
        ObjectMapper mapper = new ObjectMapper();
        mapper.readerForUpdating(report).readValue(json);
  
        report.update()
        ok(Json.toJson(report));
    }
}
```

Test:
```
@Test
public saveAndRetrieve() throws Exception {
    Report report = new Report();
    ReportSection section = new TitleSection("Working Title");
    report.sections.put("0", section);
    report.save();

    Report retrievedReport = new Model.Finder<Report>().byId(repot.id);
    ReportSection retrievedSection = retrievedReport.get("0");

    assertEquals(section, retrievedSection);
}
```

Essentially I was hoping to not have to deal with JsonNodes and just be able to work with any type of Object but it was saved by being serialized to JSON.

**Comment by rbygrave** [comment]
Just changed "Feature Request" to "ENH" to be consistent with other enhancement request titles.

**Comment by rbygrave** [comment]
For example:

```java

  // map to JSON, if not Postgres because we put length = 700
  // ...this will map to VARCHAR(700) rather than CLB

  @DbJson(length = 700)
  Set<PlainBean> beanSet;

  // JSONB (fallback to CLOB for H2 etc)

  @DbJsonB
  List<PlainBean> beanList;

  // Map where the value type is not Object so will use Jackson ObjectMapper

  @DbJson(length = 700)
  Map<String,PlainBean> beanMap = new LinkedHashMap<String, PlainBean>();

  // Not a basic List/Set/Map of String/Long/Object so use ObjectMapper

  @DbJson(length = 500)
  PlainBean plainBean;

```
