### ISSUE TITLE
Q: Removing an object from a @OneToMany collection should set the mapping field to null?

### ISSUE THREAD

**Issue by jokester01au** [ebean-orm/avaje-ebeanorm#547]
I have the following simple entities:

```
@Entity
 public class Customer extends Model {

    @OneToMany(cascade = ALL, fetch = EAGER, mappedBy="customer")
    public Set<AnOrder> order;

    @Id
    public Long id;
 }

@Entity
public class AnOrder extends Model {
    @ManyToOne
    public Customer customer;

    @Id
    public Long id;
}
```

If I excercise this like so:

```
        Customer c = new Customer();
        c.order = new HashSet<>();
        AnOrder o = new AnOrder();
        c.order.add(o);
        c.save();

        Customer cc = Ebean.getServer(null).find(Customer.class).where().eq("id", c.id).findUnique();
        System.out.println("Should have an entry: " + cc.order);

        cc.order.removeIf(oo -> oo.id == o.id);
        cc.save();

        cc.refresh();
        System.out.println("Should be empty: " + cc.order);

        cc = Ebean.getServer(null).find(Customer.class).fetch("order").where().eq("id", c.id).findUnique();
        System.out.println("Should be empty: " + cc.order);

        AnOrder oo = Ebean.getServer(null).find(AnOrder.class).where().eq("id", o.id).findUnique();
        System.out.println("Should be null: " + oo.customer);
```

then I expect `cc.order` to be empty and `oo.customer` to be null. Instead, cc.order still contains an order object and oo.customer still points to c. If I look at the database the customer_id field has not been set to null like I would expect.

NB I realise that adding @PrivateOwned to the `order` declaration would cause the order to be removed from customer, but it would also delete the order record, which is not what I want.

**Comment by dastultz** [comment]
On Sun, Jan 31, 2016 at 12:08 AM, Joseph Thomas-Kerr <
notifications@github.com> wrote:

> If I excercise this like so:
>
>         Customer c = new Customer();
>         corder = new HashSet<>();
>         AnOrder o = new AnOrder();
>         corderadd(o);
>         csave();
>
>
The problem here is you are initializing Customer.order. You should not do
that. Let Ebean initialize it and you'll get a BeanSet which will tracks
adds and removes. You need Cascade.PERSIST at a minimum for Customer to
save it, which you have. Also, the fetch settings have no effect, it
doesn't work like JPA.

/Daryl

**Comment by jokester01au** [comment]
Thanks for your response

>  Let Ebean initialize it and you'll get a BeanSet which will tracks adds and removes.

In actual fact that is exactly what I am doing in the real code from which I distilled this example. In fact for @OneToMany, the BeanSet does NOT track removals, which I do not understand. This is specifically my problem.

> Also, the fetch settings have no effect, it doesn't work like JPA.

This is not actually correct. I only added the fetch because otherwise the println was giving me `BeanSet deferred`. Given that I have specified that Customer.order be EAGER, I think that this is another bug, but I do not care about that right now.

**Comment by dastultz** [comment]
On Sun, Jan 31, 2016 at 7:32 PM, Joseph Thomas-Kerr <
notifications@github.com> wrote:

> Thanks for your response
>
> Let Ebean initialize it and you'll get a BeanSet which will tracks adds
> and removes.
>
> In actual fact that is exactly what I am doing in the real code from which
> I distilled this example.
>
I don't understand why you presented a code sample that doesn't represent
what the real problem is. I also find it difficult to read the code as
there aren't any periods in it.

If you try again with a more complete code sample that represents the
failing code, I might be able to help. At the present I can't see anything
unexpected happening.

/Daryl

**Comment by jokester01au** [comment]
There are periods in my version. They don't seem to be appearing on yours for some reason. I have edited my response to provide much more detail. Please see above.

**Comment by rbygrave** [comment]
> removing an entity from a @OneToMany relation MUST result in the linking field being set to null, and saving the One side of this relation should save this change

Why do you say that?  This is your question is it?

It almost sounds like you just want to change the order setting the customer to null - is that the case?

Just to point out that Ebean will not work as you have it without getters and setters per say. The public field style only works with play framework.

Cheers, Rob.

**Comment by jokester01au** [comment]
> Why do you say that? This is your question is it? It almost sounds like you just want to change the order setting the customer to null - is that the case?

I don't understand how it could be any other way. As it is at the moment, the BeanSet that is loaded as a @OneToMany relation seems to do nothing persistent at all. That is additions or removals to `Customer.order` do not result in any persistent change.

Is this by design? This seems incorrect to me.

> Just to point out that Ebean will not work as you have it without getters and setters per say. The public field style only works with play framework.

Good point. I am indeed using play framework and enhancement, and the enhancement operates as I would expect.

**Comment by rbygrave** [comment]
> Is this by design?

Yes.

Specifically it is expected that you would instead  'set the customer to null' on the order instance.

There should be no need for the implicit behaviour I think you are suggesting/expected  implicitly

**Comment by jokester01au** [comment]
OK, that answers my question. This doesnt seem intuitive to me. I would expect that removing an order from the list of `Customer.order` should indeed cause the order to be no longer associated with the customer.

The way that it currently is,

```
cc.order.remove(oo);
cc.save();
cc.refresh();
```

will leave cc.order unchanged. This is, as I said, unintuitive to me.

But now that I know this I can make it so in my application by explicitly setting the modify listener to ALL and then making sure that the modified elements are saved as part of a preUpdate hook.

Thanks,
Joe.

**Comment by rbygrave** [comment]
Ok. Your suggested approach does not seem sensible to me. Why not just modify the order?  That then matches the change.

Just to point out ... The ManyToOne is the side that owns the underlying foreign key/relationship. The @PrivateOwned typically represents a strong ownership (the child can't live by itself) ... So wanting to null out the customer is not consistent with that.

Cheers, Rob.
