### ISSUE TITLE
ENH: Add generated file warning to DB migration XML files

### ISSUE THREAD

**Issue by elennick** [ebean-orm/avaje-ebeanorm#550]
Would it be possible to add the option to flag migration XML files with a "**THIS IS A GENERATED FILE - DO NOT MODIFY**" warning in a comment at the top of each migration file? Since these migrations need to be persisted and likely checked into version control, it'd be really nice to make sure somebody who does not understand the entire migration process doesn't try to manually modify these files.

**Comment by rbygrave** [comment]
Yes, we could add a flag for people that want to include a warning like that.

Note that ultimately it is expected that some people will want to include a "change set" that is manually defined (like inserting data).  That needs to be better defined/documented etc as to how that is expected to happen (given that usually both the migration XML and DDL is generated together - in 1 step).

**Comment by rbygrave** [comment]
So set DbMigrationConfig.includeGeneratedFileComment = true ... and the migration xml includes the comment:

```xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- THIS IS A GENERATED FILE - DO NOT MODIFY -->
<migration xmlns="http://ebean-orm.github.io/xml/ns/dbmigration">
    <changeSet type="apply">
      ...
    </changeSet>
</migration>

```
