### ISSUE TITLE
DDL - DB Migration refactor - remove rollback.ddl generation (ultimately not used by FlywayDb etc)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#559]
This is a refactor / cleanup based on the issue that we generate the rollback ddl script for DB migration but it is not going to be used by FlywayDb for example.  We can rollback a decent number of DDL changes but not all - for example, rolling back a drop column to add the column back is potentially questionable.

Ultimately many people are obviously not needing the rollback script part so in that sense we are better off removing that altogether and leaving no ambiguity.

This change effectively removes the support for generating the 'rollback ddl' for db migrations.

Note that internally (in DdlWriter) this means we ONLY need to support the 'drop all' script generation (which is very useful for testing etc) and have renamed some internal objects to reflect that this is now their purpose.

**Comment by dastultz** [comment]
I'm not sure I accept the rationale here for dropping rollback generation (or I'm not understanding what was done). We use Liquibase along with a tool I developed to generate DDL. We make a best effort to write rollback code when we can. Certainly you can't drop a column and re-add it and get your data back, but often it's simply about keeping the schema working. In a team environment when you have a number of different branches of code in progress with different schemas, it's useful to rollback a change in order to switch to a coworker's branch and test/review. Plus people make mistakes and mess up other people's work, so it comes in handy there. We NEVER rollback in production. So that's my (more than) 2 cents. I don't think this issue will affect me since it would be a long time before we'd even be able to consider having Ebean generate DDL.

**Comment by rbygrave** [comment]
Fair comment there.

I'll try putting it another way.  If we decide that Rollback DDL is not useful for production then the question becomes is it useful for developers.

You make the point that it can be useful when switching between branches for test/review. I buy that thought but right now I believe there are other options to tackle the branch switching that mean I would not use the db migration rollback ddl to support that.

- The tendency to use the create-all and drop-all ddl scripts. For most developer and CI testing this approach works well and would be used.

- Adding the ability to run/test all the migration scripts via Ebean (without needing Liquibase or FlywayDb).  We can then also get a "create all" via running all the migration scripts for example.

- Providing good seed and example data loading mechanisms. An important part of the create-all type strategy for testing.

- Transparently using H2 for testing when the target DB is Postgres, MySql, Oracle etc.  To me this works pretty well. Obviously it doesn't cover many raw sql cases and DB specific features so mileage varies. The CI server building Ebean has 2 jobs - one running all tests against H2 and another running all tests against Postgres for example with some tests only running against H2 and some only against Postgres.

I'm open to the idea that the rollback ddl could be useful for the developer branch switching case but right now I don't expect to hit that once the other points above are addressed fully.  If it doesn't work out as planned I might put it back in.

Also to go off topic a little bit, for performance/scaling testing (but unrelated to schema changes) the desire is to:

- Providing / collecting good random data population mechanisms for scaling/performance testing

**Comment by dastultz** [comment]
Yes, there are better ways of doing things then what our shop is doing now. We're embarking on a new architecture in parallel with the existing, so hopefully we bring ideas like these along, too. Thanks.

**Comment by rbygrave** [comment]
I realise you know the following background Daryl but others won't so to fill in the back story.

**"How to test"**
In the past Ebean has not made "how to test" as easy or as **important** as it should be. The priority on this has changed and certainly I have a lot of focus on this area now. We've got some nice little improvements in this "how to test" area in recent times but I'm keen to hear about and push forward any improvements.

**DDL Generation**
DDL generation was not a top priority for Ebean for quite some time. This is now no longer the case for a number of reasons but effectively we now want Ebean to have first class DDL generation for DB migration and testing purposes.  Actually the DDL generation and DB migration is really good now - I'm very happy with where this is at (a truck load of effort has gone into this).
