### ISSUE TITLE
DDL DB Migration - change "ddl.migration.pendingDrop" to "ddl.migration.pendingDropsFor"

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#561]
So when generating a migration as the "pending drops from a prior migration" ... the current system property setting of "ddl.migration.pendingDrop" is not very clear and instead we want to change this to "ddl.migration.pendingDropsFor".

Context:

```java

// generate the next migration as ... applying the drops from the prior migration version 1.2
System.setProperty("ddl.migration.pendingDropsFor", "1.2");

DbMigration dbMigration = new DbMigration();
dbMigration.setPlatform(DbPlatformName.POSTGRES);
dbMigration.generateMigration();
```

**Comment by qadam** [comment]
[Latest documentation](http://ebean-orm.github.io/docs/setup/dbmigration) still contains example code of old property `ddl.migration.pendingDrop`

Can you update please?

**Comment by rbygrave** [comment]
Well, I think the documentation is all correct - that page contains:

```java
//System.setProperty("ddl.migration.pendingDropsFor", "1.2");
```

There seems to be only that one example so I think it is all good.

**Comment by qadam** [comment]
There is an other one in the **Applying pending drops** section

**Comment by rbygrave** [comment]
Found and fixed now - thanks.
