### ISSUE TITLE
ENH: Add ability to configure eBean to use true "ilike" expression

### ISSUE THREAD

**Issue by mutovkin** [ebean-orm/avaje-ebeanorm#570]
Currently when a query is built ilike is replaced with something like this
`lower(field_name) like term` in Postgres in order to optimize _ilike_ queries I'm using _gin_trgm_ops_ index. With _lower()_ call Postgres is not using the index.

If my understanding is incorrect what is a way to configure eBean to use true ilike?

Thank you.

**Comment by rbygrave** [comment]
You can always use the raw() expression so:
```java

String bindValue = "rob";

query.where().raw("myName ILIKE ?", bindValue);
```

But ... you are telling me that you are getting a different execution plan.  Can you confirm that and put the 2 plans in here.  My current understanding is that there should not be much of a difference at all so I'm keen to find out more here.

Thanks, Rob.

**Comment by mutovkin** [comment]
Rob, thank you for your reply. 
I indeed used _raw()_ yesterday not only for ilike but also for tsvector searches. raw() works as expected. I will have to go over my codebase and find other _ilike_ calls and replace them with raw as well as I've added this useful index (_gin_trgm_ops_) in multiple places.

Here is execution plan **with ilike**:
`
SELECT poi_id FROM poi WHERE name ilike '%york%';
Bitmap Heap Scan on public.poi  (cost=32.12..91.19 rows=15 width=8) (actual time=0.216..1.842 rows=337 loops=1)                   
  Output: poi_id                                                                                                                  
  Recheck Cond: ((poi.name)::text ~~* '%york%'::text)                                                                             
  Heap Blocks: exact=323                                                                                                          
  ->  Bitmap Index Scan on idx_poi_name_trgm_gin  (cost=0.00..32.11 rows=15 width=0) (actual time=0.157..0.157 rows=337 loops=1)  
        Index Cond: ((poi.name)::text ~~* '%york%'::text)                                                                         
Planning time: 1.421 ms                                                                                                           
Execution time: 1.932 ms `

And here is execution plan with _lower()_:
`SELECT poi_id FROM poi WHERE lower(name) like '%york%';
Seq Scan on public.poi  (cost=0.00..26918.57 rows=1215 width=8) (actual time=1.001..198.994 rows=337 loops=1)  
  Output: poi_id                                                                                               
  Filter: (lower((poi.name)::text) ~~ '%york%'::text)                                                          
  Rows Removed by Filter: 151508                                                                               
Planning time: 0.072 ms                                                                                        
Execution time: 199.065 ms   
`
That's in PostgreSQL 9.4.

eBean is a fantastic piece of software, thank you Rob!

**Comment by rbygrave** [comment]
Wow .. Interesting difference in the plans there.

Yes it would be good to be able to either:
- be able to configure use of native ilike
- support both native and lower options

Raw is almost ok but not ideal.

I'll leave this open with a view to looking at this.

Cheers, Rob.

**Comment by bukajsytlos** [comment]
Sorry if my question is stupid, but isn't this just problem of non
functional index. If index is created on column name and query is using
lower(name) and therefore not using index?

Thanks

**Comment by mutovkin** [comment]
@bukajsytlos Definitely query is not using the index. But I don't think assumption should be that index should be built for a specific implementation of an ORM framework. In my case I can't easily go and change production indices.

**Comment by bukajsytlos** [comment]
I agree. I was just curious about Rob's excitement about different
execution plans. I am no db guru, so  I just want to be sure I understand
problem here or there is something more extraordinary.

**Comment by rbygrave** [comment]
>  I just want to be sure I understand problem here

Quite right and I haven't got the full understanding of it myself. According to those plans there is a difference between ilike and lower() for the query optimiser.  The Postgres docs on WHY the difference exists is a bit light (at least what I've found it yet) but it seems the only difference is the way locale is treated.

> Rob's excitement about different execution plans.

Well, using the index is usually critical for a query like this to the point that if you don't hit the index you almost can't use the feature in production (too slow, too expensive).  So yes, this is all about ... how to index specifically for this use case and making sure we hit the index for this use case.

Could be a bug in the query optimiser?  Yes, maybe but I suspect not and ideally I reproduce this myself.

My thought is that ilike gets different treatment because the underlying index is GIN based (Inverted) and not a BTree one. Inverted indexes are not supported on every DBMS etc.

@mutovkin Can you provide the DDL used to create the index?  Then I can look to reproduce and play around with it and confirm my thinking (on why ilike gets special treatment)  - thanks, Rob.

**Comment by mutovkin** [comment]
The way I create this index is (for any table with varchar name column)

```sql
CREATE INDEX idx_name_trgm_gin ON poi USING gin(name gin_trgm_ops);
```

if you want lower to work as fast:

```sql
CREATE INDEX idx_lname_trgm_gin ON poi USING gin(lower(name) gin_trgm_ops);
```

**Comment by rbygrave** [comment]
This can be turned on via ebean.properties or ServerConfig.

```properties
## Use db native ILIKE expression if supported (ie. only on Postgres currently)
ebean.expressionNativeIlike=true
```

When this is turned on (and using Postgres) then:
```java
  Ebean.find(Customer.class)
        .where().ilike("name", "rob")
        .findList();
``

Results in the db native `ilike` expression being used:
```sql
select t0.id ... from o_customer t0 where t0.name ilike ? ; --bind(rob)
```
