### ISSUE TITLE
Q: Can ServerConfig.setJars() method support wildcard ?

### ISSUE THREAD

**Issue by xxcode-monkey** [ebean-orm/avaje-ebeanorm#572]
Currently `ServerConfig.setJars()`  must give the full name of jar like `example-1.6.jar` , can support `example-*.jar` or something kindly support update dependence

**Comment by rbygrave** [comment]
It already does/should but you need to leave off the *.jar suffix ... so just use "example-" and it should work as expected.

**Comment by rbygrave** [comment]
That should sort it. I'll close assuming that is the case.
