### ISSUE TITLE
Deprecated Joda Time API - LocalDate.toDateMidnight() usage causes exception to be thrown, change to LocalDate.toDateTimeAtStartOfDay()

### ISSUE THREAD

**Issue by bacilla-ru** [ebean-orm/avaje-ebeanorm#578]
Class `com.avaje.ebeaninternal.server.type.ScalarTypeJodaLocalDate`, line 31.
Deprecation link:
http://www.joda.org/joda-time/apidocs/org/joda/time/LocalDate.html#toDateMidnight--
Example date is 1 april 1982 in Europe/Moscow time zone.

**Comment by rbygrave** [comment]
Right, so changing the implementation to use toDateTimeAtStartOfDay() instead.

**Comment by rbygrave** [comment]
Done, thanks.

**Comment by bacilla-ru** [comment]
Seems like lines 20 and 36 needs to be fixed too.

**Comment by rbygrave** [comment]
Quite right.

Line 20 -> Fix that
Line 30 -> change to use convertToMillis();
Line 36 -> change to use convertToDate();

**Comment by rbygrave** [comment]
So that looks all better now. If you can sanity check that would be great.  I refactored a touch just to reuse the convertToMillis() and convertToDate() methods.

Thanks, Rob.
