### ISSUE TITLE
Unique index or primary key violation - double insert attempted on ManyToMany intersection

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#600]
The scenario is fairly intricate.

- bean "A" has 2 ManyToMany relationships to different types "B" and "C"
- bean "C" is saved with both directions set "C" -> "A" and "A" - "C"  (leaving "A" -> "C" in dirty state after save)
- bean "B" is saved ... with cascade to "A" on so B cascade saves  "B" -> "A" ... which cascades to "A" -> "C" ... which then tries to insert the duplicate row from the initial save of "C".

**Comment by rbygrave** [comment]
So the fix here was to add to DefaultPersister ... saveMany.resetModifyState() line 927 .. which means that the side that doesn't get to maintain the intersection has it's modify state reset.

**Comment by dastultz** [comment]
Fix confirmed, thanks.
