### ISSUE TITLE
ManyToOne returns wrong ID value (prior ManyToOne with inheritance and null value).  Regression introduced in 7.2.1.

### ISSUE THREAD

**Issue by dastultz** [ebean-orm/avaje-ebeanorm#610]
7.2.1 appears to have introduce a regression with OneToOne. The primary key of the mapped entity is not correct, it's actually the PK of a different entity in the parent.

Attached test case. Test passes with 7.1.1.

[ebean-bug-submit.zip](https://github.com/ebean-orm/avaje-ebeanorm/files/182390/ebean-bug-submit.zip)

**Comment by rbygrave** [comment]
Great thanks. I've run and test and reproduced. Looking into it now.

**Comment by rbygrave** [comment]
Just confirming that yes, I introduced this issue as part of #595 commit cf62ea4

Specifically, when reading an assoc one (ManyToOne or OneToOne) that has inheritance and is null ... this commit introduces the bug where by the discriminator is read (and is null) but the id property is not ignored.  So yes, no test case covering that scenario.

**Comment by dastultz** [comment]
Fixed confirmed. Thanks for the quick turn around.
