### ISSUE TITLE
Bean update not persisting

### ISSUE THREAD

**Issue by sirsavary** [ebean-orm/avaje-ebeanorm#613]
I am attempting to triage a small project using Ebean and SQLite. For some reason, when attempting to update a field on an entity, Ebean will not persist the changes to the database.

The line in question: https://github.com/vandenmax1/LibraryDatabase/blob/master/src/main/java/sample/Controller.java#L187

The logs from before and after that line:
```
03:18:34.318 [JavaFX Application Thread] TRACE org.avaje.ebean.TXN - txn[1001] Begin
03:18:34.348 [JavaFX Application Thread] DEBUG org.avaje.ebean.SQL - txn[1001] select t0.id c0, t0.created_at c1, t0.student_id c2, t0.first_name c3, t0.last_name c4, t0.updated_at c5 from student t0 where t0.student_id = ? ; --bind(328854989)
03:18:34.351 [JavaFX Application Thread] DEBUG org.avaje.ebean.SUM - txn[1001] FindMany type[Student] origin[ijYgH.h7iWz.DXcpNW] exeMicros[6378] rows[1] name[] predicates[t0.student_id = ? ] bind[328854989]
03:18:34.353 [JavaFX Application Thread] DEBUG org.avaje.ebean.SQL - txn[1001] select t0.id c0, t0.created_at c1, t0.time_in c2, t0.time_out c3, t0.was_manual c4, t0.updated_at c5, t0.student_id c6 from sign_in t0 where t0.student_id = ?  order by t0.time_in desc limit 1; --bind(1)
03:18:34.353 [JavaFX Application Thread] DEBUG org.avaje.ebean.SUM - txn[1001] FindMany type[SignIn] origin[CzyG2g.h7iW3.DXcpNW] exeMicros[465] rows[1] name[] predicates[t0.student_id = ? ] bind[1]
03:18:34.356 [JavaFX Application Thread] TRACE org.avaje.ebean.TXN - txn[1001] Commit - query only
```

The entity is created in the database just fine, inspection of the database shows that it is there. Updating it is the only issue. I have tried updating other fields on it without any success.

**Comment by rbygrave** [comment]
You need to use a setter method (setTimeout) ... So that the bean is marked
as dirty.

Cheers, Rob.

**Comment by sirsavary** [comment]
Why do we need to use a setter if we're using the Ebean enhancement plugin? I use Ebean with Play! Framework and the enhancement plugin and have never needed to use setters (or getters).

**Comment by rbygrave** [comment]
Play is doing some enhancement that converts those GETFIELD and PUTFIELD calls into getter/setter method calls.

So just using public fields is a Play thing (not an Ebean thing).

Ebean needs to detect/change 'setting values' and Ebean's enhancement replaces PUTFIELD calls (in setter methods) so do dirty checking.  Ebean does this enhancement on the bean.

Play's enhancement has to change any/all callers of those public fields to use setters/getters ... to this enhancement is not limited to the actual entity beans but ANYTHING that is accessing those fields.

Unfortunately Play haven't really explained that to people and many think public fields 'just work' but no they don't (without the application wide enhancement that Play is doing).

Does that clarify it a bit?
Are you all good?

**Comment by rbygrave** [comment]
I'll assume you are all good and close this.  Post back if you need more clarification.

Thanks, Rob.

**Comment by sirsavary** [comment]
No, that clarifies everything. Wasn't aware that it was a Play specific thing. Thank you very much.
