### ISSUE TITLE
Clustering can not support properties file?

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#623]
I can not found configure `Clustering` from file

**Comment by rbygrave** [comment]
Is this question:

How do you configure clustering using properties file?

**Comment by icode** [comment]
yes, i can't find configure from code (`config.loadFromProperties`)

**Comment by rbygrave** [comment]
Yes I understand. As part of this I'll look to break out the clustering communication/transport as at some future point we need environment specific discovery (node discovery specific to AWS etc).

**Comment by rbygrave** [comment]
So this is fixed with 7.5.1 (which also has pulled out the clustering communication into separate module(s) and includes the avaje-ebeanorm-cluster dependency with tcp socket based clustering support).

So for this issue we can go:
```properties
ebean.cluster.active=true
ebean.cluster.localHostPort=127.0.0.1:9942
ebean.cluster.members=127.0.0.1:9942,127.0.0.1:9943
```

**Comment by icode** [comment]
This has problem, because other configure server can use `PropertiesWrapper` connect multi db, a application has more db. So, this should be use `PropertiesWrapper` and use `cluster.active` property, remove `ebean.` string

**Comment by rbygrave** [comment]
Your statement is not clear to me.

**Comment by icode** [comment]
App has two database, so two EbeanServer. EbeanServer1 connect  `db1`, EbeanServer2 connect `db2`. Then EbeanServer1 EbeanServer2 must be different `ContainerConfig`

**Comment by rbygrave** [comment]
Nope. 1 container holds multiple EbeanServer instances.  The cluster
communication is per container and uses the EbeanServer name ("db1" and
"db2") to know which instance the cluster message relates to.

So no we only need one configuration.

**Comment by icode** [comment]
Nope. db1 db2 is different data, different business, different table scheme. db1 is my owner, db2 is buy other service data.

**Comment by rbygrave** [comment]
That does not matter at all.

**Comment by icode** [comment]
So, the server name should be consistent?

**Comment by rbygrave** [comment]
The EbeanServer name needs to be consistent across the cluster (so that the
messages go to the matching EbeanServer instance on the other members of
the cluster).

So you want "db1" to be the same yes (logically the same EbeanServer
instances).
