### ISSUE TITLE
ENH: Add Hazelcast L2 cache plugin option

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#635]
Add a L2 cache plugin using Hazelcast.

**Options:**
**L2 Query cache**:  This will only be 'Near cache'.  Remote cache not useful for L2 Query cache.

**L2 Bean cache**: It would be good to support 3 options here where L2 means local/near cache and L3 means remote/cluster cache

1. L2 (Near cache only) ...

2. L2 + L3 (So LRU Near cache that is then backed by the cluster,  This gives us the performance of near cache hits and when we miss (due to LRU/size of near cache etc) we hit the cluster cache so we still don't hit the database.  The implication is that for updates we invalidate the near caches (via remove) and update the cluster cache (put delta) so updates are a little more expensive (vs much faster reads with hits against near cache.

3. L3 So no near cache, all requests go to the cluster.

We would chose L3 when the cardinality is really high for that bean type (e.g. millions of orders so too many beans to cache locally and  low % hit rate on near cache so best just to always go remote).

We would chose L2 + L3 when the cardinality is relatively low and updates fairly rare (e.g. Countries, Currencies have low cardinality and infrequent updates).

Use L2 only when we are just happy to hit the DB more (find by primary key is fast).

**Comment by icode** [comment]
support Apache Ignite?

**Comment by rbygrave** [comment]
I'll definitely have a look at this yes ... looks impressive.

**Comment by icode** [comment]
look this benchmark https://ignite.apache.org/benchmarks/ignite-vs-hazelcast.html

**Comment by rbygrave** [comment]
Looks impressive.  I'll sort out Hazelcast first, they look very similarly
featured so should be easy once Hazelcast is done.

**Comment by icode** [comment]
Hazelcast is commercial project, this is worrying, like h2 database more features need buy it.

**Comment by icode** [comment]
https://apacheignite.readme.io/docs/maven-setup Ignite can use for embeded application

**Comment by rbygrave** [comment]
So from the work last night I have both Hazelcast and Ignite working.

However, Ignite is looking very compelling so I'm swapping the priorities such that Ignite is first priority. Specifically there are some features and configuration that we really want to take advantage of.

So people watching this should start watching: 
https://github.com/ebean-orm/avaje-ebeanorm/issues/638
https://github.com/ebean-orm/avaje-ebeanorm-ignite

**Comment by rbygrave** [comment]
Thanks @icode for pushing the case for Ignite.

**Comment by rbygrave** [comment]
Release avaje-ebeanorm-hazelcast version 1.1.1

Include it in the classpath and it will automatically become the L2 cache implementation. You can optionally define a hazelcast-client.xml (or hazelcast.xml) to configure specific caches (bean caches only).  You need a hazelcast-client.xml to configure a near-cache for example.

**Comment by rbygrave** [comment]
Relating this to release 7.7.1
