### ISSUE TITLE
ENH: Add type support for java.nio.file.Path ... such that it stores the underlying URI as VARCHAR/string

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#651]
support java.io.File and java.nio.file.Path save to db.

db data type use `Blob`, can configure save file bytes or file path.

add `plan` column can use for witch read file bytes or file path, both plan use
 
and more info last modified, size, filename and more

**Comment by rbygrave** [comment]
You need to expand and explain more clearly exactly what is desired.

Ebean already supports java.io.File - it streams into a DB Clob or Blob type.

**Comment by icode** [comment]
save file has two way

1. save file content bytes
2. save file OS location (file path)

sometimes, we need save file content to db. and sometimes, we save file path, read system path.

so, we need switch save plan.

**Comment by rbygrave** [comment]
Yes, I don't think I like this option 2. of having Ebean store the file
path. Whenever I have needed to store a 'file path' I have done this in my
application (so the entity bean has a String property for the path). That
means the application can deal with relative paths, temp directories, S3
paths etc.

I don't see option 2 as a good thing for Ebean to do.

Saving the File content however is really good because it handles the
streaming aspect making it really easy to deal with large content
(streaming the content into and out of the DB).

... but no I don't see "2. save file OS location (file path)" as something
Ebean should do but instead application code should do.

**Comment by icode** [comment]
save file content to db is low read speed at DB date too large.
but small application and small data save file content to DB is easy and convenience.

about support `java.nio.Path`

`Path` can custom `FileSystem` , so file can save any way (SASS, HDFS, S3 etc) and not change code.

**Comment by icode** [comment]
and how to read bytes streaming? not all bytes

**Comment by rbygrave** [comment]
> how to read bytes streaming? not all bytes

Do you mean how to stream only part of the bytes?  You can't, you need to use the java.sql.Clob API to do that. With the File type all the bytes are streamed in and out.

> about support java.nio.Path

You can just do Path.toFile() in the application of course but sure.  Is that what you want this ticket to be? An enhancement request to add support for java.nio.Path?

**Comment by icode** [comment]
`Path` can support muitl file type and transparent for developer

**Comment by rbygrave** [comment]
Is that what you want this ticket to be? 

An enhancement request to add support for java.nio.Path (just like the current File support) ?

**Comment by icode** [comment]
`File` != `Path.toFile()` because `Path` can any protocol, http HDSF etc.

**Comment by icode** [comment]
en, like current File support, but `Path` should save `Path.toString()` or `URI` ?

**Comment by rbygrave** [comment]
That is not how File support works.  **File support is used to stream the content into/out of the DB**.  It is NOT used to store the file **path**.

If you want Path.toString() etc then no, I will not add support for that as per the prior comments.

**Comment by icode** [comment]
support `Path` user can less code.

```
// read file from db
Paths.get(URI.create("db:///xxx/1"));
// read file from http
Paths.get(URI.create("http://www.xx.com/1"));
// read file from hdfs
Paths.get(URI.create("hdfs:///a/1"));
// etc ..
```

save path `Path.toUri()` to DB.

**Comment by icode** [comment]
and developer can do not know file how to save, any `FileSystem`.

```
Files.size(path);
Files.getLastModifiedTime(path);
Files.readAllBytes(path);
// etc ...
```

**Comment by icode** [comment]
You understand what I'm saying what?

**Comment by rbygrave** [comment]
I think you want to support the Path type specifically by persisting the URI string value and then converting that back from String to URI to Path.

Is that correct?

**Comment by icode** [comment]
yes, but not change code, use `Path` not `URI`. 

see https://docs.oracle.com/javase/8/docs/technotes/guides/io/fsp/filesystemprovider.html

and can use api `Paths.get(uri)`

**Comment by icode** [comment]
`Path` like  Apache Commons VFS and best

**Comment by rbygrave** [comment]
Ok done and pushed.  Supports Path ... by translating it into a String via URI to save as VARCHAR.

**Comment by rbygrave** [comment]
I'll close this now.  Let me know if that is different to what you expect.
