### ISSUE TITLE
DDLGenerator - Don't drop tables or don't throw errors for existing tables

### ISSUE THREAD

**Issue by mhlz** [ebean-orm/avaje-ebeanorm#654]
For ease of deployment, I like to let tables and schemas be generated on the fly. EBean only seems to support this with dropping all data that is already there (which is nice for testing, not so nice for production).

Setting createOnly to true results in error when starting up the application since the relations already exist.

I'd like to be able to configure EBean so, that no errors are thrown for existing relations during startup.

I do know that you should ideally design the schema yourself to have a better performance, I find it much easier though (especially with PaaS in mind) to just throw my application somewhere and let it install the things it needs.

**Comment by mhlz** [comment]
I solved my specific problem using the following Kotlin code:

        val server = EbeanServerFactory.create(config)

        config.isDdlGenerate = true
        config.isDdlRun = true
        config.isDdlCreateOnly = true

        val generator = object : DdlGenerator(server as SpiEbeanServer, config) {

            private var createAllContent: String? = null

            override fun runCreateSql() {
                if (createAllContent == null) {
                    createAllContent = readFile(createFileName)
                }
                runScript(true, createAllContent, createFileName)
            }
        }

        generator.execute(true)

**Comment by rbygrave** [comment]
> support this with dropping all data that is already there

Not really. DB Migration was built just for this purpose I would say: 
http://ebean-orm.github.io/docs/setup/dbmigration

... and yes Ebean ought to be able to run the migration without requiring FlywayDB etc via enhancement request #636 

So the create-all / drop-all scripts are absolutely only intended for running tests and DB Migration is used to apply schema DIFF's to an existing database (aka prod, pre-prod, test etc)

Your suggestion will not quite work in a number of cases which DB migration takes account of such as:
- Drops : These need to be held back etc
- Order of changes: Changes to foreign keys, History tables etc need to execute in a correct order

I definitely recommend using DB migration for this.

**Comment by rbygrave** [comment]
I'll assume my answer above satisfied your question and close this. Re-open to discuss more if required etc.

Cheers, Rob.
