### ISSUE TITLE
Documentation of ebean

### ISSUE THREAD

**Issue by apachemaven** [ebean-orm/avaje-ebeanorm#66]
Hi:

I have used Ebean before, and it seems that new version(3.2.4) is available , however the documentation is rather  out of date, the reference(http://www.avaje.org/doc/ebean-userguide.pdf) is written at 2010 and focused on 2.6.0.

Then I wonder if latest documentation is available?

**Comment by ForNeVeR** [comment]
Wow, you really should add a link there to the `Readme.md`, to the repository settings, everywhere! It really provides some useful information.

**Comment by rbygrave** [comment]
Ok, I think we have made enough progress on http://ebean-orm.github.io/ ... so closing this. Always more documentation to be done but getting good traction on this now.
