### ISSUE TITLE
ENH: Add  deletePermanent(beanType, id) and deleteAllPermanent(beanType, ids) ... (basically missing API)

### ISSUE THREAD

**Issue by xxcode-monkey** [ebean-orm/avaje-ebeanorm#661]
There have  `delete(bean,id)` and `deleteAll(beans,ids)` but no  `deletePermanent(bean,id)` and `deleteAllPermanent(beans,ids)` , miss something or for some other reason?

**Comment by rbygrave** [comment]
I'll have a look at this later today.  I think those methods should be added.

**Comment by rbygrave** [comment]
So yes, added the extra 2 methods for deletePermanent() and deleteAllPermanent() ... taking beanType and id or ids.
