### ISSUE TITLE
deleteAll(beans) return int , but deleteAll(beanType,ids) return void in EbeanServer

### ISSUE THREAD

**Issue by xxcode-monkey** [ebean-orm/avaje-ebeanorm#666]
I'm curious about why `deleteAll(beans)` return `int` , but `deleteAll(beanType,ids)` return `void` in `EbeanServer` . and`save` `insert` `update` ...  the same

**Comment by rbygrave** [comment]
For deleteAll() I'll change those to all return int.

saveAll(), insertAll(), updateAll() are much less interesting as they don't have the bulk statement mechanism that delete can use.  I'm not sure if returning int for saveAll(), insertAll() or updateAll() is actually useful or informative.

So for this I'm changing the deleteAll() methods to return int.
