### ISSUE TITLE
SPAM

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#676]
REMOVED (Questions goto Ebean google group)

**Comment by rbygrave** [comment]
As per the recent post to the google group - https://groups.google.com/forum/#!topic/ebean/MyQsya9HuVw

Github issues are only to be used for Bugs and Enhancement requests.  All questions must be posted to the google group and not here as github issues.

**Comment by rbygrave** [comment]
As per the policy here ... http://ebean-orm.github.io/support ... I will remove this content.
