### ISSUE TITLE
Refactor - rename @CacheStrategy to @Cache ... require explicit enableQueryCache=true for query cache use

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#684]
So this is a couple of changes:

- Rename @CacheStrategy to @Cache
- Add enableQueryCache() default false;
- Add enableBeanCache() default true; 

This means that we effectively **enable** the use of bean caching and query caching explicitly.  This means that at startup time the EbeanServer knows which caches will be used and need invalidation etc (and that this will not change during runtime).

**Comment by rbygrave** [comment]
This also means that useBeanCache() is removed.  Effectively it's enableBeanCache() now.
```java
// this is removed ... basically use enableBeanCache now
boolean useBeanCache() default true;
```

**Comment by rbygrave** [comment]
This commit / change also includes a refactoring of how the caches are initialised during EbeanServer startup.  To enable that ServerCacheFactory has been changed and ServerCachePlugin added such that the ServerCacheFactory can be created early.  I'll log this as another ticket even though it is included in this commit.

**Comment by almothafar** [comment]
OMG, please update socuments in website them I was wondering where ` @CacheStrategy ` gone
