### ISSUE TITLE
SPAM

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#687]
Removed (as question that should be posted to Ebean google group)

**Comment by rbygrave** [comment]
Ask questions on the google group forum - do not ask questions here.  This is not a bug.

I will block people who ask questions via github issues.

**Comment by icode** [comment]
this is bug, not support, no questions

**Comment by rbygrave** [comment]
For this issue and from now on I will get you to post the issue to the Ebean google group. We can discuss the issue there until there is sufficient information to log an issue and I will log the issue into github on your behalf.

I will now get you to post this issue to the Ebean google group and we will progress it from there.

Thanks, Rob.
