### ISSUE TITLE
@Id not work for sqlite

### ISSUE THREAD

**Issue by GreatFireWall** [ebean-orm/avaje-ebeanorm#690]
## Expected behavior
a field in my class: 
```java
@Id
private long id;
```
I expected it will autoincrement even I never set its value.

## Actual behavior
Infact, there's an exception thrown if I never set a value to id that greater than 0;
![image](https://cloud.githubusercontent.com/assets/4510984/14976169/ea6a3640-113b-11e6-8ebf-520caf072605.png)

### Steps to reproduce
first, make a simple class like this:
![image](https://cloud.githubusercontent.com/assets/4510984/14976188/210202fa-113c-11e6-93b7-255c34868909.png)

then you do this, will reproduce
```Java
    ChunkModel model = new ChunkModel();
    ebeanServer.save(model);
```

**Comment by rbygrave** [comment]
Hi, I will get you to log this issue on the Ebean google group forum and we can discuss it from there. https://groups.google.com/forum/#!forum/ebean

Thanks, Rob.
