### ISSUE TITLE
Q: DbMigrationConfig.migrationPath represent different value for DbMigration and MigrationRunner

### ISSUE THREAD

**Issue by wjtan** [ebean-orm/avaje-ebeanorm#691]
The same setting for `DbMigrationConfig.migrationPath` cannot be used for both `DbMigration` and `MigrationRunner`.

To generate sql and xml are in the directory `conf/dbmigration`,
```
DbMigrationConfig config = new DbMigrationConfig();
config.setMigrationPath("dbmigration");
....
DbMigration dbMigration = new DbMigration();
dbMigration.setPathToResources("conf");
dbMigration.generateMigration();

```
To access the generated sql and xml correctly:
```
EbeanServer server = Ebean.getDefaultServer();

DbMigrationConfig config = new DbMigrationConfig();
config.setMigrationPath("filesystem:conf/dbmigration");

new MigrationRunner(server, config).run();
```

**Comment by rbygrave** [comment]
Hi, I will get you to log this issue on the Ebean google group forum and we can discuss it from there. https://groups.google.com/forum/#!forum/ebean

Thanks, Rob.

**Comment by rbygrave** [comment]
This issue was moved to the forum for discussion. closing.
