### ISSUE TITLE
History DDL generation for Postgres does not respect non-public schema

### ISSUE THREAD

**Issue by npokr** [ebean-orm/avaje-ebeanorm#698]
## Expected behavior

Have a @History entity that specifies a schema (in this case "gen")

```java
@History
@Entity
@Table(name = "o_country", schema = "gen")
public class Country ...

```

Generate the DDL.

## Actual behavior

The generated table, history table and history view are all good.

The issue is with the stored procedure in that it does not use the schema.  The effect of this is that when the history trigger fires to insert into the history table this fails with an error.

```console
  ERROR: relation "o_country_history" doe snot exist Where: PL/pgSQL function o_country_history_version() line 4 at SQL statement
```

The generated stored procedure (that is missing the use of "gen" schema is):

```sql
create or replace function o_country_history_version() returns trigger as $$
begin
  if (TG_OP = 'UPDATE') then
    insert into o_country_history (sys_period,code, name) values (tstzrange(lower(OLD.sys_period), current_timestamp), OLD.code, OLD.name);
    NEW.sys_period = tstzrange(current_timestamp,null);
    return new;
  elsif (TG_OP = 'DELETE') then
    insert into o_country_history (sys_period,code, name) values (tstzrange(lower(OLD.sys_period), current_timestamp), OLD.code, OLD.name);
    return old;
  end if;
end;
$$ LANGUAGE plpgsql;
```

**Comment by rbygrave** [comment]
With this fixed the resulting ddl is:

Note the "gen" schema used in the procedure name, internally in the procedure and also the trigger.

```sql
alter table gen.o_country add column sys_period tstzrange not null default tstzrange(current_timestamp, null);
create table gen.o_country_history(like gen.o_country);
create view gen.o_country_with_history as select * from gen.o_country union all select * from gen.o_country_history;

create or replace function gen.o_country_history_version() returns trigger as $$
begin
  if (TG_OP = 'UPDATE') then
    insert into gen.o_country_history (sys_period,code, name) values (tstzrange(lower(OLD.sys_period), current_timestamp), OLD.code, OLD.name);
    NEW.sys_period = tstzrange(current_timestamp,null);
    return new;
  elsif (TG_OP = 'DELETE') then
    insert into gen.o_country_history (sys_period,code, name) values (tstzrange(lower(OLD.sys_period), current_timestamp), OLD.code, OLD.name);
    return old;
  end if;
end;
$$ LANGUAGE plpgsql;

create trigger o_country_history_upd
before update or delete on gen.o_country
for each row execute procedure gen.o_country_history_version();
```

So the fix here is just to remove the 'normalisation' of the table name (which strips the schema and quoted identifiers).  This might be a problem if/when people desire to use quoted identifiers with @History (but we might have a problem there anyway).  I personally discourage the use of quoted identifiers so I'm happy enough to not handle that case and see if the need actually arises.

So yes, I'm happy enough with this fix (removing the normalisation of the base table name).
