### ISSUE TITLE
MySQL - Tables w/ reserved names

### ISSUE THREAD

**Issue by jjlauer** [ebean-orm/avaje-ebeanorm#705]
Is there a way to use the table name such as `order` with MySQL?  If I manually escape the table using backticks then mysql will allow it.  With ebean I simply get an exception when I query or insert into that table. I didn't see any obvious way to get ebean to escape table names by default.  Curious if this can work or if I simply need to rename my table.

**Comment by rbygrave** [comment]
Hi Joe, with this project we have a policy of NOT asking questions as github issues as per: http://ebean-orm.github.io/support 

Please re-post your question to the Ebean google group: https://groups.google.com/forum/#!forum/ebean

Thanks, Rob.
