### ISSUE TITLE
Remove createNamedQuery() and createQuery(Class<T> beanType, String query) ... use criteria API, query beans and RawSql

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#716]
So with this we are removing support for using the query language in the form of named queries and via the createQuery() method.

This was raised on the google group as: https://groups.google.com/forum/#!topic/ebean/XeP1qoESQj8

### Removing from EbeanServer and Ebean
```java
  <T> Query<T> createQuery(Class<T> beanType, String query);

  <T> Query<T> createNamedQuery(Class<T> beanType, String namedQuery);
```
This also has the effect of removing the use of orm.xml (which held named queries etc).

The effect of this changes means that we must create queries using criteria, query beans or RawSql.

The motivation for this that query beans and finders etc bring strongly type checking and represent a better way to build queries (and no one defended the use of named queries and query language use).

**Comment by rbygrave** [comment]
This also removes

```java
 Update<T> createNamedUpdate(Class<T> beanType, String namedUpdate) {

 SqlQuery createNamedSqlQuery(String namedQuery);

 SqlUpdate createNamedSqlUpdate(String namedQuery);

```

**Comment by robertofabrizi** [comment]
> This also removes
> 
> ```java
>  Update<T> createNamedUpdate(Class<T> beanType, String namedUpdate) {
> 
>  SqlQuery createNamedSqlQuery(String namedQuery);
> 
>  SqlUpdate createNamedSqlUpdate(String namedQuery);
> ```

Me again! Too bad, I needed this to write queries without having to recompile anything, the usage scenario is something like Kibana, where you write a query to output aggregate data to be rendered on the frontend as charts or gauges or pies. Being able to write these queries in a xml, not having a bean behind them due to their nature, would have been a great plus.
