### ISSUE TITLE
ENH: Add endOr(), endAnd(), endNot() ... to ExpressionList as synonym for endJunction()

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#727]
So with ExpressionList when we use for example and() we can end that with endAnd() or endJunction().

That is, endOr(), endAnd(), endNot() are just synonyms for endJunction().

Why add these synonyms?  Well, because endJunction() is slightly technical and I think it will be easier for people reading expressions to read endAnd().

Did these exist before and you removed them Rob?  Yes and yes.  These synonyms existed before and I removed them when we added `must()`, `should()` and `mustNot()` as part of the ElasticSearch query support.  I thought to remove endAnd(), endOr() because I didn't think it made sense to also have endMust(), endShould() etc.

Now, I'm adding them back because I think endAnd(), endOr(), endNot() are the common case (well, most common case) and that the pain/hassle of having these synonyms is offset by better readability.  That is a round about way I saying I think I was wrong to remove them earlier.

So yes, this means instead of endJunction() we can use endAnd():

```java
    Ebean.find(Customer.class)
      .where()
      .or()
        .and()
          .startsWith("name", "r")
          .eq("anniversary", onAfter)
          .endAnd()
        .and()
          .eq("status", Customer.Status.ACTIVE)
          .gt("id", 0)
          .endAnd()
        .orderBy().asc("name")
        .findList();
```

**Comment by wenzhihong2003** [comment]
in query bean project the `TQRootBean` method `endOr` `endEnd` 's Deprecated flag must be remove. `endNot` will be add.

**Comment by rbygrave** [comment]
> query bean project the TQRootBean method ...

Quite right.  Sorted now as https://github.com/ebean-orm/avaje-ebeanorm-querybean/issues/25

Thanks, Rob.
