### ISSUE TITLE
ENH: Add support for using ebean.mf manifest file for finding/defining packages to search for entities 

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#731]
This makes sense to use when a jar of domain objects is built.  It can contain `META-INF/ebean.mf` manifest file with a `packages:` entry to define the package(s) that contain entity beans and then Ebean can automatically know where to scan/find entity bean classes.

Example 1 manifest contents:
```console
packages:  com.myco.foo.domain, com.myco.bar.domain
```

Example 2 
```console
packages:  com.myco.foo.domain
```

**Comment by woderchen** [comment]
hi，
i'm using single jar for entity.  once run server,  below error appears:
**** is NOT an Entity Bean registered with this server?

i'm sure entity has been enhanced, and add @entity to entity class,  ebean.search.jars is not working, seems it was work well before(version:7.11).   now the ebeanorm is 7.14.1
so i need to use ebean.mf to avoid the issue?

**Comment by rbygrave** [comment]
> so i need to use ebean.mf to avoid the issue?

No.

Please post questions on the Ebean forum: https://groups.google.com/forum/#!forum/ebean

Posting on github issues effectively spams 48 people and we don't want that ... so please ask questions on the Ebean forum first.  Thanks.
