### ISSUE TITLE
a question about 'order by' with keyword 'desc'

### ISSUE THREAD

**Issue by sfwn** [ebean-orm/avaje-ebeanorm#787]
I'm a Chinese and my English is poor. I can't guarantee whether I could describe the question clearly to you. There is something I'm confused.   
My develop environment is: kotlin + ebean-orm + spring-boot + mysql.  
I have a model written in kotlin, which has a property called "desc" means "describe". I know that "desc" is also a keyword in mysql, so I add a annotation `@Column` above "desc" and you can see below:  
My model:
```kotlin
@Entity
@Table(name = "ps_table")
class MyModel {

    companion object {
        val find = object : Find<Long, MyModel>() {}
    }

    // other properties

    var taskId: String? = null

    @Column(name = "`desc`")
    var desc: String? = null

    @CreatedTimestamp
    open var createdAt: Date? = null

}
```
Now my aid is to get the descend(who's abbr is also "desc") ordered data.  
My service method in below:  
```kotlin
fun xxxMethod_1(): List<AAA> {
    return AlarmRule.find.where().eq("taskId", taskId).orderBy().desc("createdAt").findList()
}
```
When I invoked this method, I got an error below:
```
There was an unexpected error (type=Internal Server Error, status=500).
org.springframework.web.util.NestedServletException: Request processing failed; 
nested exception is javax.persistence.PersistenceException: 
Query threw SQLException:You have an error in your SQL syntax; 
check the manual that corresponds to your MySQL server version 
for the right syntax to use near 't0.`desc`' at line 1 Bind values:
[MACHINE,true] Query was: select t0.task_id c1, t0.`desc` c2, t0.created_at c3 
from ps_table t0 where t0.taskId = ? order by t0.created_at t0.`desc`
```
Something strange. I set only ONE property "createdAt" to descend order my data, but in fact ebean-orm ordered according to TWO properties(Is my understanding right?). so error happens.

I have found a way to solve my problem. My solution code is:
```kotlin
    fun xxxMethod_2(): List<AAA> {
        return OrderBy<MyModel>().run {
            query = MyModel.find.where().eq("taskId", taskId).query()
            desc("createdAt")
        }.findList()
    }
```
In this way, I can get the right data descend ordered by property "createdAt".

And, if I still used the "xxxMethod_1" but I remove the property "desc" in MyModel, I also can get the right result. So I think the reason is in resolving the keyword "desc".

Of course, I don't know if it is a bug in ebean-orm, or there are some mechanisms I don't know yet. Please tell me and teach me more. 

Thank you anyway :)

**Comment by rbygrave** [comment]
Ah, this looks like a bug where:

```sql
order by t0.created_at desc
```
Gets translated by Ebean into:
```sql
order by t0.created_at t0.`desc`
```

So Ebean is translating the `desc` keyword into the property and putting in the column reference of `t0.'desc'`.

There is a problem here in that Ebean allows expressions like case statements etc to be used in the orderBy clause.  So this is way Ebean does a translation of "logical properties" to "db columns" on the order by clause ... hence `desc` is getting "translated" to the mapped DB column.

So this bug would also occur if you have a bean property called `asc`.

The workaround would be to change the bean property name from `desc` to `description`:

```java
    @Column(name = "`desc`")
    var description: String? = null
```

... and in this way the "desc" in  `order by t0.created_at desc` ... would not get translated.

**Comment by rbygrave** [comment]
As a side remark - your English is very good and you have done an excellent job of describing your issue.

Well done!!

**Comment by sfwn** [comment]
@rbygrave  
Thank you for your reply and I know how to fix my problem~
This is the first time I asked on GitHub and surprisedly got an answer! Extremely exciting!

**Comment by rbygrave** [comment]
I'll close this issue for now.  At this stage we have the limitation that bean property names should not be the keywords `desc` or `asc`.

I think that is reasonable at the moment. We can revisit if others hit this down the track.

**Comment by richdrich** [comment]
We have also tickled this bug - our database uses `desc` for 'Description' in a few places.
